// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_otp.proto

package VK_Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 请求服务
type OTPOps int32

const (
	OTPOps_Req_OTP_Voice           OTPOps = 1
	OTPOps_Req_OTP_Verify          OTPOps = 2
	OTPOps_Req_OTP_Zz253           OTPOps = 3
	OTPOps_Req_OTP_CleanCode       OTPOps = 4
	OTPOps_Req_OTP_SendMail        OTPOps = 5
	OTPOps_Req_OTP_VerifyMail      OTPOps = 6
	OTPOps_Req_OTP_SendPhoneCode   OTPOps = 7
	OTPOps_Req_OTP_VerifyPhoneCode OTPOps = 8
	OTPOps_Req_OTP_PhoneNum        OTPOps = 9
)

var OTPOps_name = map[int32]string{
	1: "Req_OTP_Voice",
	2: "Req_OTP_Verify",
	3: "Req_OTP_Zz253",
	4: "Req_OTP_CleanCode",
	5: "Req_OTP_SendMail",
	6: "Req_OTP_VerifyMail",
	7: "Req_OTP_SendPhoneCode",
	8: "Req_OTP_VerifyPhoneCode",
	9: "Req_OTP_PhoneNum",
}
var OTPOps_value = map[string]int32{
	"Req_OTP_Voice":           1,
	"Req_OTP_Verify":          2,
	"Req_OTP_Zz253":           3,
	"Req_OTP_CleanCode":       4,
	"Req_OTP_SendMail":        5,
	"Req_OTP_VerifyMail":      6,
	"Req_OTP_SendPhoneCode":   7,
	"Req_OTP_VerifyPhoneCode": 8,
	"Req_OTP_PhoneNum":        9,
}

func (x OTPOps) Enum() *OTPOps {
	p := new(OTPOps)
	*p = x
	return p
}
func (x OTPOps) String() string {
	return proto.EnumName(OTPOps_name, int32(x))
}
func (x *OTPOps) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OTPOps_value, data, "OTPOps")
	if err != nil {
		return err
	}
	*x = OTPOps(value)
	return nil
}
func (OTPOps) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

// VoiceOTPReq sms验证码 请求
type VoiceOTPReq struct {
	Phone            *string `protobuf:"bytes,1,req,name=Phone" json:"Phone,omitempty"`
	PlayerID         *int64  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoiceOTPReq) Reset()                    { *m = VoiceOTPReq{} }
func (m *VoiceOTPReq) String() string            { return proto.CompactTextString(m) }
func (*VoiceOTPReq) ProtoMessage()               {}
func (*VoiceOTPReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *VoiceOTPReq) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *VoiceOTPReq) GetPlayerID() int64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

// VerifyOTPReq 验证用户输入的验证码 请求
type VerifyOTPReq struct {
	Phone            *string `protobuf:"bytes,1,opt,name=Phone" json:"Phone,omitempty"`
	Code             *string `protobuf:"bytes,2,req,name=Code" json:"Code,omitempty"`
	PlayerID         *int64  `protobuf:"varint,3,opt,name=PlayerID" json:"PlayerID,omitempty"`
	UnCleanCode      *bool   `protobuf:"varint,4,opt,name=UnCleanCode" json:"UnCleanCode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyOTPReq) Reset()                    { *m = VerifyOTPReq{} }
func (m *VerifyOTPReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyOTPReq) ProtoMessage()               {}
func (*VerifyOTPReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *VerifyOTPReq) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *VerifyOTPReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *VerifyOTPReq) GetPlayerID() int64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *VerifyOTPReq) GetUnCleanCode() bool {
	if m != nil && m.UnCleanCode != nil {
		return *m.UnCleanCode
	}
	return false
}

// VerifyTelegramOTPResp 验证用户输入的验证码 回复
type VerifyTelegramOTPResp struct {
	En               *int32  `protobuf:"varint,1,req,name=En" json:"En,omitempty"`
	Phone            *string `protobuf:"bytes,2,opt,name=Phone" json:"Phone,omitempty"`
	TelegramUserId   *string `protobuf:"bytes,3,opt,name=TelegramUserId" json:"TelegramUserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyTelegramOTPResp) Reset()                    { *m = VerifyTelegramOTPResp{} }
func (m *VerifyTelegramOTPResp) String() string            { return proto.CompactTextString(m) }
func (*VerifyTelegramOTPResp) ProtoMessage()               {}
func (*VerifyTelegramOTPResp) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *VerifyTelegramOTPResp) GetEn() int32 {
	if m != nil && m.En != nil {
		return *m.En
	}
	return 0
}

func (m *VerifyTelegramOTPResp) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *VerifyTelegramOTPResp) GetTelegramUserId() string {
	if m != nil && m.TelegramUserId != nil {
		return *m.TelegramUserId
	}
	return ""
}

// EMailReq 发送邮件
type SendEMail struct {
	To               *string `protobuf:"bytes,1,req,name=To" json:"To,omitempty"`
	Body             *string `protobuf:"bytes,2,opt,name=Body" json:"Body,omitempty"`
	Subject          *string `protobuf:"bytes,3,opt,name=Subject" json:"Subject,omitempty"`
	PlayerID         *int64  `protobuf:"varint,4,opt,name=PlayerID" json:"PlayerID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendEMail) Reset()                    { *m = SendEMail{} }
func (m *SendEMail) String() string            { return proto.CompactTextString(m) }
func (*SendEMail) ProtoMessage()               {}
func (*SendEMail) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *SendEMail) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *SendEMail) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *SendEMail) GetSubject() string {
	if m != nil && m.Subject != nil {
		return *m.Subject
	}
	return ""
}

func (m *SendEMail) GetPlayerID() int64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

// VerifyEMail 验证邮箱
type VerifyEMail struct {
	To               *string `protobuf:"bytes,1,req,name=To" json:"To,omitempty"`
	Code             *string `protobuf:"bytes,2,req,name=Code" json:"Code,omitempty"`
	UnCleanCode      *bool   `protobuf:"varint,3,opt,name=UnCleanCode" json:"UnCleanCode,omitempty"`
	PlayerID         *int64  `protobuf:"varint,4,opt,name=PlayerID" json:"PlayerID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyEMail) Reset()                    { *m = VerifyEMail{} }
func (m *VerifyEMail) String() string            { return proto.CompactTextString(m) }
func (*VerifyEMail) ProtoMessage()               {}
func (*VerifyEMail) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *VerifyEMail) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *VerifyEMail) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *VerifyEMail) GetUnCleanCode() bool {
	if m != nil && m.UnCleanCode != nil {
		return *m.UnCleanCode
	}
	return false
}

func (m *VerifyEMail) GetPlayerID() int64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

// LoadEMail 获取邮箱
type LoadEMail struct {
	EMail            *string `protobuf:"bytes,1,req,name=EMail" json:"EMail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoadEMail) Reset()                    { *m = LoadEMail{} }
func (m *LoadEMail) String() string            { return proto.CompactTextString(m) }
func (*LoadEMail) ProtoMessage()               {}
func (*LoadEMail) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *LoadEMail) GetEMail() string {
	if m != nil && m.EMail != nil {
		return *m.EMail
	}
	return ""
}

// SendPhoneCodeReq 发送手机认证码
type SendPhoneCodeReq struct {
	Phone            *string `protobuf:"bytes,1,req,name=Phone" json:"Phone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendPhoneCodeReq) Reset()                    { *m = SendPhoneCodeReq{} }
func (m *SendPhoneCodeReq) String() string            { return proto.CompactTextString(m) }
func (*SendPhoneCodeReq) ProtoMessage()               {}
func (*SendPhoneCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *SendPhoneCodeReq) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

// VerifyPhoneCode 生成手机认证码
type VerifyPhoneCodeReq struct {
	Phone            *string `protobuf:"bytes,1,req,name=Phone" json:"Phone,omitempty"`
	Code             *string `protobuf:"bytes,2,req,name=Code" json:"Code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyPhoneCodeReq) Reset()                    { *m = VerifyPhoneCodeReq{} }
func (m *VerifyPhoneCodeReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyPhoneCodeReq) ProtoMessage()               {}
func (*VerifyPhoneCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

func (m *VerifyPhoneCodeReq) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *VerifyPhoneCodeReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// PhoneCodeNumRsp 发送验证码次数
type PhoneCodeNumRsp struct {
	CurNum           *int32 `protobuf:"varint,1,req,name=CurNum" json:"CurNum,omitempty"`
	TotalNum         *int32 `protobuf:"varint,2,req,name=TotalNum" json:"TotalNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PhoneCodeNumRsp) Reset()                    { *m = PhoneCodeNumRsp{} }
func (m *PhoneCodeNumRsp) String() string            { return proto.CompactTextString(m) }
func (*PhoneCodeNumRsp) ProtoMessage()               {}
func (*PhoneCodeNumRsp) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *PhoneCodeNumRsp) GetCurNum() int32 {
	if m != nil && m.CurNum != nil {
		return *m.CurNum
	}
	return 0
}

func (m *PhoneCodeNumRsp) GetTotalNum() int32 {
	if m != nil && m.TotalNum != nil {
		return *m.TotalNum
	}
	return 0
}

type PhoneCodeNumReq struct {
	Phone            *string `protobuf:"bytes,1,req,name=Phone" json:"Phone,omitempty"`
	Num              *int32  `protobuf:"varint,2,opt,name=Num" json:"Num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhoneCodeNumReq) Reset()                    { *m = PhoneCodeNumReq{} }
func (m *PhoneCodeNumReq) String() string            { return proto.CompactTextString(m) }
func (*PhoneCodeNumReq) ProtoMessage()               {}
func (*PhoneCodeNumReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{9} }

func (m *PhoneCodeNumReq) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *PhoneCodeNumReq) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*VoiceOTPReq)(nil), "VK.Proto.VoiceOTPReq")
	proto.RegisterType((*VerifyOTPReq)(nil), "VK.Proto.VerifyOTPReq")
	proto.RegisterType((*VerifyTelegramOTPResp)(nil), "VK.Proto.VerifyTelegramOTPResp")
	proto.RegisterType((*SendEMail)(nil), "VK.Proto.SendEMail")
	proto.RegisterType((*VerifyEMail)(nil), "VK.Proto.VerifyEMail")
	proto.RegisterType((*LoadEMail)(nil), "VK.Proto.LoadEMail")
	proto.RegisterType((*SendPhoneCodeReq)(nil), "VK.Proto.SendPhoneCodeReq")
	proto.RegisterType((*VerifyPhoneCodeReq)(nil), "VK.Proto.VerifyPhoneCodeReq")
	proto.RegisterType((*PhoneCodeNumRsp)(nil), "VK.Proto.PhoneCodeNumRsp")
	proto.RegisterType((*PhoneCodeNumReq)(nil), "VK.Proto.PhoneCodeNumReq")
	proto.RegisterEnum("VK.Proto.OTPOps", OTPOps_name, OTPOps_value)
}

func init() { proto.RegisterFile("client_otp.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0xaf, 0xd2, 0x40,
	0x14, 0x4d, 0xa7, 0x94, 0x47, 0x2f, 0x8a, 0xf3, 0x6e, 0xe0, 0x89, 0xba, 0xc1, 0x2e, 0x4c, 0xe3,
	0xe2, 0x2d, 0x34, 0x2e, 0xdc, 0x68, 0x22, 0xb2, 0x78, 0x51, 0xa1, 0x99, 0xd7, 0xc7, 0xc2, 0x0d,
	0xa9, 0x70, 0x55, 0x4c, 0xe9, 0x94, 0xd2, 0x9a, 0xe0, 0xff, 0xf4, 0xff, 0x98, 0x99, 0x7e, 0xd0,
	0x82, 0xe8, 0xee, 0xde, 0x33, 0x73, 0xcf, 0x3d, 0xe7, 0x4c, 0x0b, 0x7c, 0x19, 0xae, 0x29, 0x4a,
	0x17, 0x32, 0x8d, 0xaf, 0xe3, 0x44, 0xa6, 0x12, 0x3b, 0xf3, 0x0f, 0xd7, 0x9e, 0xaa, 0x9c, 0xb7,
	0xd0, 0x9d, 0xcb, 0xf5, 0x92, 0x66, 0xbe, 0x27, 0x68, 0x8b, 0x7d, 0xb0, 0xbc, 0xef, 0x32, 0xa2,
	0xa1, 0x31, 0x62, 0xae, 0x2d, 0xf2, 0x06, 0x1f, 0x43, 0xc7, 0x0b, 0x83, 0x3d, 0x25, 0x37, 0xef,
	0x87, 0x6c, 0x64, 0xb8, 0xa6, 0xa8, 0x7a, 0xe7, 0x27, 0xdc, 0x9b, 0x53, 0xb2, 0xfe, 0xba, 0x3f,
	0x65, 0x30, 0x0e, 0x0c, 0x08, 0xad, 0xb1, 0x5c, 0xd1, 0x90, 0x69, 0x5a, 0x5d, 0x37, 0x58, 0xcd,
	0x26, 0x2b, 0x8e, 0xa0, 0x7b, 0x17, 0x8d, 0x43, 0x0a, 0x22, 0x3d, 0xd6, 0x1a, 0x19, 0x6e, 0x47,
	0xd4, 0x21, 0x87, 0x60, 0x90, 0xef, 0xf5, 0x29, 0xa4, 0x6f, 0x49, 0xb0, 0xd1, 0xfb, 0x77, 0x31,
	0xf6, 0x80, 0x4d, 0x22, 0xad, 0xdf, 0x12, 0x6c, 0x12, 0x1d, 0x04, 0xb1, 0xba, 0xa0, 0x67, 0xd0,
	0x2b, 0x07, 0xef, 0x76, 0x94, 0xdc, 0xac, 0xb4, 0x04, 0x5b, 0x1c, 0xa1, 0x0e, 0x81, 0x7d, 0x4b,
	0xd1, 0x6a, 0xf2, 0x29, 0x58, 0x87, 0x8a, 0xda, 0x97, 0x45, 0x34, 0xcc, 0x97, 0xca, 0xd5, 0x3b,
	0xb9, 0xda, 0x17, 0xcc, 0xba, 0xc6, 0x21, 0x5c, 0xdc, 0x66, 0x5f, 0x7e, 0xd0, 0x32, 0x2d, 0x18,
	0xcb, 0xb6, 0xe1, 0xb7, 0x75, 0x94, 0xa2, 0x84, 0x6e, 0xee, 0xe6, 0xec, 0xa2, 0x93, 0xf8, 0x8e,
	0x22, 0x32, 0x4f, 0x22, 0xfa, 0xe7, 0xc2, 0xa7, 0x60, 0x7f, 0x94, 0x41, 0xe1, 0xab, 0x0f, 0x96,
	0x2e, 0xca, 0x57, 0xd7, 0x8d, 0xe3, 0x02, 0x57, 0xd6, 0x75, 0x5e, 0x8a, 0xef, 0xec, 0xf7, 0xe1,
	0xbc, 0x01, 0xcc, 0xd5, 0xff, 0xff, 0xee, 0xdf, 0xac, 0x38, 0x13, 0x78, 0x50, 0x4d, 0x4e, 0xb3,
	0x8d, 0xd8, 0xc5, 0x78, 0x05, 0xed, 0x71, 0x96, 0x4c, 0xb3, 0x4d, 0xf1, 0x92, 0x45, 0xa7, 0x3c,
	0xf9, 0x32, 0x0d, 0x42, 0x75, 0xc2, 0xf4, 0x49, 0xd5, 0x3b, 0xaf, 0x8f, 0x68, 0xce, 0x6a, 0xe0,
	0x60, 0xe6, 0xf3, 0x86, 0x6b, 0x09, 0x55, 0x3e, 0xff, 0x6d, 0x40, 0x7b, 0xe6, 0x7b, 0xb3, 0x78,
	0x87, 0x97, 0x70, 0x5f, 0xd0, 0x76, 0x31, 0xf3, 0xbd, 0x85, 0xfe, 0x33, 0xb8, 0x81, 0x08, 0xbd,
	0x0a, 0xd2, 0x3e, 0x39, 0xab, 0x5f, 0xfb, 0xfc, 0xeb, 0xc5, 0xab, 0x97, 0xdc, 0xc4, 0x01, 0x5c,
	0x96, 0x50, 0xf5, 0x08, 0xbc, 0x85, 0x7d, 0xe0, 0x25, 0xac, 0xf2, 0x54, 0xd9, 0x72, 0x0b, 0xaf,
	0x00, 0x9b, 0x9c, 0x1a, 0x6f, 0xe3, 0x23, 0x18, 0xd4, 0x6f, 0x57, 0x86, 0xf8, 0x05, 0x3e, 0x81,
	0x87, 0xcd, 0x91, 0xc3, 0x61, 0xa7, 0xbe, 0x45, 0xc3, 0xd3, 0x6c, 0xc3, 0xed, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0a, 0x22, 0x91, 0x0e, 0xfb, 0x03, 0x00, 0x00,
}
