// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_milepost.proto

package VK_Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 里程碑任务信息
type MilepostActivityItem struct {
	Id               *int32              `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	NeedValue        *int64              `protobuf:"varint,2,req,name=NeedValue" json:"NeedValue,omitempty"`
	Type             *int32              `protobuf:"varint,3,req,name=Type" json:"Type,omitempty"`
	Status           *MilepostStatus     `protobuf:"varint,4,req,name=Status,enum=VK.Proto.MilepostStatus" json:"Status,omitempty"`
	Rewards          []*PropExchangeData `protobuf:"bytes,5,rep,name=Rewards" json:"Rewards,omitempty"`
	BetValue         *int64              `protobuf:"varint,6,req,name=BetValue" json:"BetValue,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MilepostActivityItem) Reset()                    { *m = MilepostActivityItem{} }
func (m *MilepostActivityItem) String() string            { return proto.CompactTextString(m) }
func (*MilepostActivityItem) ProtoMessage()               {}
func (*MilepostActivityItem) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *MilepostActivityItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MilepostActivityItem) GetNeedValue() int64 {
	if m != nil && m.NeedValue != nil {
		return *m.NeedValue
	}
	return 0
}

func (m *MilepostActivityItem) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MilepostActivityItem) GetStatus() MilepostStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return MilepostStatus_MS_Invalid
}

func (m *MilepostActivityItem) GetRewards() []*PropExchangeData {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MilepostActivityItem) GetBetValue() int64 {
	if m != nil && m.BetValue != nil {
		return *m.BetValue
	}
	return 0
}

// 里程碑活动信息
type MilepostActivityInfo struct {
	IsOpen                *bool                   `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	StartTime             *int64                  `protobuf:"varint,2,req,name=StartTime" json:"StartTime,omitempty"`
	EndTime               *int64                  `protobuf:"varint,3,req,name=EndTime" json:"EndTime,omitempty"`
	ConfigId              *int32                  `protobuf:"varint,4,req,name=ConfigId" json:"ConfigId,omitempty"`
	Tasks                 []*MilepostActivityItem `protobuf:"bytes,5,rep,name=tasks" json:"tasks,omitempty"`
	Status                *MilepostStatus         `protobuf:"varint,6,req,name=Status,enum=VK.Proto.MilepostStatus" json:"Status,omitempty"`
	RechargeNum           *int64                  `protobuf:"varint,7,req,name=RechargeNum" json:"RechargeNum,omitempty"`
	NeedRechargeNum       *int64                  `protobuf:"varint,8,req,name=NeedRechargeNum" json:"NeedRechargeNum,omitempty"`
	NeedRechargeNumOfWeek *int64                  `protobuf:"varint,9,req,name=NeedRechargeNumOfWeek" json:"NeedRechargeNumOfWeek,omitempty"`
	XXX_unrecognized      []byte                  `json:"-"`
}

func (m *MilepostActivityInfo) Reset()                    { *m = MilepostActivityInfo{} }
func (m *MilepostActivityInfo) String() string            { return proto.CompactTextString(m) }
func (*MilepostActivityInfo) ProtoMessage()               {}
func (*MilepostActivityInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *MilepostActivityInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *MilepostActivityInfo) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *MilepostActivityInfo) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *MilepostActivityInfo) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *MilepostActivityInfo) GetTasks() []*MilepostActivityItem {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *MilepostActivityInfo) GetStatus() MilepostStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return MilepostStatus_MS_Invalid
}

func (m *MilepostActivityInfo) GetRechargeNum() int64 {
	if m != nil && m.RechargeNum != nil {
		return *m.RechargeNum
	}
	return 0
}

func (m *MilepostActivityInfo) GetNeedRechargeNum() int64 {
	if m != nil && m.NeedRechargeNum != nil {
		return *m.NeedRechargeNum
	}
	return 0
}

func (m *MilepostActivityInfo) GetNeedRechargeNumOfWeek() int64 {
	if m != nil && m.NeedRechargeNumOfWeek != nil {
		return *m.NeedRechargeNumOfWeek
	}
	return 0
}

// 里程碑活动领取
type ReqMilepost struct {
	Id               *int32 `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Type             *int32 `protobuf:"varint,2,req,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqMilepost) Reset()                    { *m = ReqMilepost{} }
func (m *ReqMilepost) String() string            { return proto.CompactTextString(m) }
func (*ReqMilepost) ProtoMessage()               {}
func (*ReqMilepost) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *ReqMilepost) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ReqMilepost) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 里程碑活动领取回复
type ReqMilepostRsp struct {
	Milepost         *MilepostActivityItem `protobuf:"bytes,1,req,name=Milepost" json:"Milepost,omitempty"`
	Status           *int32                `protobuf:"varint,2,req,name=Status" json:"Status,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ReqMilepostRsp) Reset()                    { *m = ReqMilepostRsp{} }
func (m *ReqMilepostRsp) String() string            { return proto.CompactTextString(m) }
func (*ReqMilepostRsp) ProtoMessage()               {}
func (*ReqMilepostRsp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *ReqMilepostRsp) GetMilepost() *MilepostActivityItem {
	if m != nil {
		return m.Milepost
	}
	return nil
}

func (m *ReqMilepostRsp) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*MilepostActivityItem)(nil), "VK.Proto.MilepostActivityItem")
	proto.RegisterType((*MilepostActivityInfo)(nil), "VK.Proto.MilepostActivityInfo")
	proto.RegisterType((*ReqMilepost)(nil), "VK.Proto.ReqMilepost")
	proto.RegisterType((*ReqMilepostRsp)(nil), "VK.Proto.ReqMilepostRsp")
}

func init() { proto.RegisterFile("client_milepost.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6b, 0xdc, 0x30,
	0x14, 0x24, 0xda, 0xac, 0xd7, 0x79, 0x81, 0x2d, 0xa8, 0x4d, 0x11, 0xa6, 0x14, 0xe3, 0x93, 0x4f,
	0xa6, 0x0d, 0x7b, 0xea, 0xad, 0x1f, 0x39, 0x98, 0xd2, 0x24, 0x28, 0x21, 0x3d, 0x06, 0x61, 0xbd,
	0xdd, 0x35, 0x59, 0x4b, 0xae, 0x25, 0xb7, 0xcd, 0x7f, 0xed, 0x4f, 0xe8, 0x8f, 0x28, 0x96, 0x2d,
	0xaf, 0x49, 0x02, 0xcd, 0xcd, 0x33, 0x6f, 0x64, 0xcd, 0x8c, 0x1e, 0x9c, 0x14, 0xbb, 0x12, 0x95,
	0xbd, 0xad, 0xca, 0x1d, 0xd6, 0xda, 0xd8, 0xac, 0x6e, 0xb4, 0xd5, 0x34, 0xbc, 0xf9, 0x9a, 0x5d,
	0x76, 0x5f, 0xd1, 0x4b, 0xb3, 0x15, 0x0d, 0xca, 0xdb, 0x42, 0x57, 0x95, 0x56, 0xfd, 0x38, 0xa2,
	0x03, 0x89, 0xaa, 0xad, 0x4c, 0xcf, 0x25, 0x7f, 0x0e, 0xe0, 0xd5, 0xb7, 0xe1, 0x2f, 0x1f, 0x0b,
	0x5b, 0xfe, 0x2c, 0xed, 0x7d, 0x6e, 0xb1, 0xa2, 0x4b, 0x20, 0xb9, 0x64, 0x07, 0x31, 0x49, 0xe7,
	0x9c, 0xe4, 0x92, 0xbe, 0x81, 0xa3, 0x73, 0x44, 0x79, 0x23, 0x76, 0x2d, 0x32, 0x12, 0x93, 0x74,
	0xc6, 0xf7, 0x04, 0xa5, 0x70, 0x78, 0x7d, 0x5f, 0x23, 0x9b, 0x39, 0xbd, 0xfb, 0xa6, 0xef, 0x20,
	0xb8, 0xb2, 0xc2, 0xb6, 0x86, 0x1d, 0xc6, 0x24, 0x5d, 0x9e, 0xb2, 0xcc, 0xdb, 0xcb, 0xfc, 0x8d,
	0xfd, 0x9c, 0x0f, 0x3a, 0xba, 0x82, 0x05, 0xc7, 0x5f, 0xa2, 0x91, 0x86, 0xcd, 0xe3, 0x59, 0x7a,
	0x7c, 0x1a, 0xed, 0x8f, 0x5c, 0x36, 0xba, 0x3e, 0xfb, 0x5d, 0x6c, 0x85, 0xda, 0xe0, 0x17, 0x61,
	0x05, 0xf7, 0x52, 0x1a, 0x41, 0xf8, 0x09, 0x6d, 0x6f, 0x2c, 0x70, 0xc6, 0x46, 0x9c, 0xfc, 0x25,
	0x4f, 0xc4, 0x53, 0x6b, 0x4d, 0x5f, 0x43, 0x90, 0x9b, 0x8b, 0x1a, 0x95, 0x8b, 0x18, 0xf2, 0x01,
	0x75, 0x31, 0xaf, 0xac, 0x68, 0xec, 0x75, 0x59, 0x8d, 0x31, 0x47, 0x82, 0x32, 0x58, 0x9c, 0x29,
	0xe9, 0x66, 0x33, 0x37, 0xf3, 0xb0, 0x33, 0xf1, 0x59, 0xab, 0x75, 0xb9, 0xc9, 0xa5, 0x8b, 0x3b,
	0xe7, 0x23, 0xa6, 0x2b, 0x98, 0x5b, 0x61, 0xee, 0x7c, 0xa8, 0xb7, 0x8f, 0x7b, 0x98, 0x36, 0xcf,
	0x7b, 0xf1, 0xa4, 0xbe, 0xe0, 0x99, 0xf5, 0xc5, 0x70, 0xcc, 0xb1, 0xd8, 0x8a, 0x66, 0x83, 0xe7,
	0x6d, 0xc5, 0x16, 0xce, 0xe1, 0x94, 0xa2, 0x29, 0xbc, 0xe8, 0xde, 0x6c, 0xaa, 0x0a, 0x9d, 0xea,
	0x21, 0x4d, 0x57, 0x70, 0xf2, 0x80, 0xba, 0x58, 0x7f, 0x47, 0xbc, 0x63, 0x47, 0x4e, 0xff, 0xf4,
	0x30, 0x79, 0xdf, 0x39, 0xf8, 0xe1, 0xed, 0x3d, 0xda, 0x21, 0xbf, 0x25, 0x64, 0xbf, 0x25, 0x89,
	0x84, 0xe5, 0xe4, 0x08, 0x37, 0x35, 0xfd, 0x00, 0xa1, 0x87, 0xee, 0xec, 0xff, 0x1b, 0x1b, 0xf5,
	0xdd, 0xb3, 0x0e, 0xa5, 0xf5, 0x77, 0x0c, 0xe8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x1d,
	0x80, 0x16, 0x31, 0x03, 0x00, 0x00,
}
