// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_rechargeactivity.proto

package VK_Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WeekRechargeTask struct {
	TaskID           *int32              `protobuf:"varint,1,req,name=TaskID" json:"TaskID,omitempty"`
	Reward           []*PropExchangeData `protobuf:"bytes,2,rep,name=Reward" json:"Reward,omitempty"`
	Status           *CommonStatus       `protobuf:"varint,3,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	Des              *string             `protobuf:"bytes,4,opt,name=Des" json:"Des,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *WeekRechargeTask) Reset()                    { *m = WeekRechargeTask{} }
func (m *WeekRechargeTask) String() string            { return proto.CompactTextString(m) }
func (*WeekRechargeTask) ProtoMessage()               {}
func (*WeekRechargeTask) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *WeekRechargeTask) GetTaskID() int32 {
	if m != nil && m.TaskID != nil {
		return *m.TaskID
	}
	return 0
}

func (m *WeekRechargeTask) GetReward() []*PropExchangeData {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *WeekRechargeTask) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *WeekRechargeTask) GetDes() string {
	if m != nil && m.Des != nil {
		return *m.Des
	}
	return ""
}

type WeekRechargeInfo struct {
	IsOpen           *bool               `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	IsCanReset       *bool               `protobuf:"varint,2,req,name=IsCanReset" json:"IsCanReset,omitempty"`
	Status           *CommonStatus       `protobuf:"varint,3,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	Number           *int32              `protobuf:"varint,4,opt,name=Number" json:"Number,omitempty"`
	BuyDate          *string             `protobuf:"bytes,5,opt,name=BuyDate" json:"BuyDate,omitempty"`
	Tasks            []*WeekRechargeTask `protobuf:"bytes,6,rep,name=Tasks" json:"Tasks,omitempty"`
	Status2          *CommonStatus       `protobuf:"varint,7,req,name=Status2,enum=VK.Proto.CommonStatus" json:"Status2,omitempty"`
	IsDone           *bool               `protobuf:"varint,8,req,name=IsDone" json:"IsDone,omitempty"`
	CanBuyWareId     *string             `protobuf:"bytes,9,req,name=CanBuyWareId" json:"CanBuyWareId,omitempty"`
	CanBuyHalfWareId *string             `protobuf:"bytes,10,req,name=CanBuyHalfWareId" json:"CanBuyHalfWareId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *WeekRechargeInfo) Reset()                    { *m = WeekRechargeInfo{} }
func (m *WeekRechargeInfo) String() string            { return proto.CompactTextString(m) }
func (*WeekRechargeInfo) ProtoMessage()               {}
func (*WeekRechargeInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *WeekRechargeInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *WeekRechargeInfo) GetIsCanReset() bool {
	if m != nil && m.IsCanReset != nil {
		return *m.IsCanReset
	}
	return false
}

func (m *WeekRechargeInfo) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *WeekRechargeInfo) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *WeekRechargeInfo) GetBuyDate() string {
	if m != nil && m.BuyDate != nil {
		return *m.BuyDate
	}
	return ""
}

func (m *WeekRechargeInfo) GetTasks() []*WeekRechargeTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WeekRechargeInfo) GetStatus2() CommonStatus {
	if m != nil && m.Status2 != nil {
		return *m.Status2
	}
	return CommonStatus_CS_Invalid
}

func (m *WeekRechargeInfo) GetIsDone() bool {
	if m != nil && m.IsDone != nil {
		return *m.IsDone
	}
	return false
}

func (m *WeekRechargeInfo) GetCanBuyWareId() string {
	if m != nil && m.CanBuyWareId != nil {
		return *m.CanBuyWareId
	}
	return ""
}

func (m *WeekRechargeInfo) GetCanBuyHalfWareId() string {
	if m != nil && m.CanBuyHalfWareId != nil {
		return *m.CanBuyHalfWareId
	}
	return ""
}

// 领取活动奖励
type WeekRechargeTaskReq struct {
	TaskID           *int32 `protobuf:"varint,1,req,name=TaskID" json:"TaskID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *WeekRechargeTaskReq) Reset()                    { *m = WeekRechargeTaskReq{} }
func (m *WeekRechargeTaskReq) String() string            { return proto.CompactTextString(m) }
func (*WeekRechargeTaskReq) ProtoMessage()               {}
func (*WeekRechargeTaskReq) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *WeekRechargeTaskReq) GetTaskID() int32 {
	if m != nil && m.TaskID != nil {
		return *m.TaskID
	}
	return 0
}

// 活动奖励领取回复
type WeekRechargeTaskResp struct {
	Reward           []*PropExchangeData `protobuf:"bytes,1,rep,name=Reward" json:"Reward,omitempty"`
	Info             *WeekRechargeInfo   `protobuf:"bytes,2,req,name=Info" json:"Info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *WeekRechargeTaskResp) Reset()                    { *m = WeekRechargeTaskResp{} }
func (m *WeekRechargeTaskResp) String() string            { return proto.CompactTextString(m) }
func (*WeekRechargeTaskResp) ProtoMessage()               {}
func (*WeekRechargeTaskResp) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *WeekRechargeTaskResp) GetReward() []*PropExchangeData {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *WeekRechargeTaskResp) GetInfo() *WeekRechargeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type RechargeExtraInfo struct {
	IsOpen           *bool              `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	Locker           *int32             `protobuf:"varint,2,req,name=Locker" json:"Locker,omitempty"`
	MinRecharge      *int32             `protobuf:"varint,3,req,name=MinRecharge" json:"MinRecharge,omitempty"`
	MaxExtra         *int32             `protobuf:"varint,4,opt,name=MaxExtra" json:"MaxExtra,omitempty"`
	Extra            *float64           `protobuf:"fixed64,5,opt,name=Extra" json:"Extra,omitempty"`
	ConfigId         *int32             `protobuf:"varint,6,req,name=ConfigId" json:"ConfigId,omitempty"`
	ExcludeGameIds   []int32            `protobuf:"varint,7,rep,name=ExcludeGameIds" json:"ExcludeGameIds,omitempty"`
	Status           *CommonStatus      `protobuf:"varint,8,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	Type             *RechargeExtraType `protobuf:"varint,9,opt,name=Type,enum=VK.Proto.RechargeExtraType" json:"Type,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RechargeExtraInfo) Reset()                    { *m = RechargeExtraInfo{} }
func (m *RechargeExtraInfo) String() string            { return proto.CompactTextString(m) }
func (*RechargeExtraInfo) ProtoMessage()               {}
func (*RechargeExtraInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *RechargeExtraInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *RechargeExtraInfo) GetLocker() int32 {
	if m != nil && m.Locker != nil {
		return *m.Locker
	}
	return 0
}

func (m *RechargeExtraInfo) GetMinRecharge() int32 {
	if m != nil && m.MinRecharge != nil {
		return *m.MinRecharge
	}
	return 0
}

func (m *RechargeExtraInfo) GetMaxExtra() int32 {
	if m != nil && m.MaxExtra != nil {
		return *m.MaxExtra
	}
	return 0
}

func (m *RechargeExtraInfo) GetExtra() float64 {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return 0
}

func (m *RechargeExtraInfo) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *RechargeExtraInfo) GetExcludeGameIds() []int32 {
	if m != nil {
		return m.ExcludeGameIds
	}
	return nil
}

func (m *RechargeExtraInfo) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *RechargeExtraInfo) GetType() RechargeExtraType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RechargeExtraType_RET_VideoCatch
}

// 拉取充值额外奖励活动
type LoadRechargeExtraReq struct {
	Type             *RechargeExtraType `protobuf:"varint,1,req,name=Type,enum=VK.Proto.RechargeExtraType" json:"Type,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LoadRechargeExtraReq) Reset()                    { *m = LoadRechargeExtraReq{} }
func (m *LoadRechargeExtraReq) String() string            { return proto.CompactTextString(m) }
func (*LoadRechargeExtraReq) ProtoMessage()               {}
func (*LoadRechargeExtraReq) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *LoadRechargeExtraReq) GetType() RechargeExtraType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RechargeExtraType_RET_VideoCatch
}

type MidMonthRechargeItme struct {
	Id               *int32        `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Recharge         *int32        `protobuf:"varint,2,req,name=Recharge" json:"Recharge,omitempty"`
	Extra            *int32        `protobuf:"varint,3,req,name=Extra" json:"Extra,omitempty"`
	Status           *CommonStatus `protobuf:"varint,4,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	WareId           *string       `protobuf:"bytes,5,req,name=WareId" json:"WareId,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MidMonthRechargeItme) Reset()                    { *m = MidMonthRechargeItme{} }
func (m *MidMonthRechargeItme) String() string            { return proto.CompactTextString(m) }
func (*MidMonthRechargeItme) ProtoMessage()               {}
func (*MidMonthRechargeItme) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *MidMonthRechargeItme) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MidMonthRechargeItme) GetRecharge() int32 {
	if m != nil && m.Recharge != nil {
		return *m.Recharge
	}
	return 0
}

func (m *MidMonthRechargeItme) GetExtra() int32 {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return 0
}

func (m *MidMonthRechargeItme) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *MidMonthRechargeItme) GetWareId() string {
	if m != nil && m.WareId != nil {
		return *m.WareId
	}
	return ""
}

type MidMonthRechargeInfo struct {
	IsOpen           *bool                   `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	Locker           *int32                  `protobuf:"varint,2,req,name=Locker" json:"Locker,omitempty"`
	StartDay         *int32                  `protobuf:"varint,3,req,name=StartDay" json:"StartDay,omitempty"`
	EndDay           *int32                  `protobuf:"varint,4,opt,name=EndDay" json:"EndDay,omitempty"`
	ConfigId         *int32                  `protobuf:"varint,5,req,name=ConfigId" json:"ConfigId,omitempty"`
	ExcludeGameIds   []int32                 `protobuf:"varint,6,rep,name=ExcludeGameIds" json:"ExcludeGameIds,omitempty"`
	Recharges        []*MidMonthRechargeItme `protobuf:"bytes,7,rep,name=Recharges" json:"Recharges,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *MidMonthRechargeInfo) Reset()                    { *m = MidMonthRechargeInfo{} }
func (m *MidMonthRechargeInfo) String() string            { return proto.CompactTextString(m) }
func (*MidMonthRechargeInfo) ProtoMessage()               {}
func (*MidMonthRechargeInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

func (m *MidMonthRechargeInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *MidMonthRechargeInfo) GetLocker() int32 {
	if m != nil && m.Locker != nil {
		return *m.Locker
	}
	return 0
}

func (m *MidMonthRechargeInfo) GetStartDay() int32 {
	if m != nil && m.StartDay != nil {
		return *m.StartDay
	}
	return 0
}

func (m *MidMonthRechargeInfo) GetEndDay() int32 {
	if m != nil && m.EndDay != nil {
		return *m.EndDay
	}
	return 0
}

func (m *MidMonthRechargeInfo) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *MidMonthRechargeInfo) GetExcludeGameIds() []int32 {
	if m != nil {
		return m.ExcludeGameIds
	}
	return nil
}

func (m *MidMonthRechargeInfo) GetRecharges() []*MidMonthRechargeItme {
	if m != nil {
		return m.Recharges
	}
	return nil
}

type WeekendRechargeItme struct {
	Id               *int32        `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Recharge         *int32        `protobuf:"varint,2,req,name=Recharge" json:"Recharge,omitempty"`
	Extra            *int32        `protobuf:"varint,3,req,name=Extra" json:"Extra,omitempty"`
	Status           *CommonStatus `protobuf:"varint,4,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	WareId           *string       `protobuf:"bytes,5,req,name=WareId" json:"WareId,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *WeekendRechargeItme) Reset()                    { *m = WeekendRechargeItme{} }
func (m *WeekendRechargeItme) String() string            { return proto.CompactTextString(m) }
func (*WeekendRechargeItme) ProtoMessage()               {}
func (*WeekendRechargeItme) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{8} }

func (m *WeekendRechargeItme) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WeekendRechargeItme) GetRecharge() int32 {
	if m != nil && m.Recharge != nil {
		return *m.Recharge
	}
	return 0
}

func (m *WeekendRechargeItme) GetExtra() int32 {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return 0
}

func (m *WeekendRechargeItme) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *WeekendRechargeItme) GetWareId() string {
	if m != nil && m.WareId != nil {
		return *m.WareId
	}
	return ""
}

type WeekendRechargeInfo struct {
	IsOpen           *bool                  `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	Locker           *int32                 `protobuf:"varint,2,req,name=Locker" json:"Locker,omitempty"`
	StartDay         *int32                 `protobuf:"varint,3,req,name=StartDay" json:"StartDay,omitempty"`
	EndDay           *int32                 `protobuf:"varint,4,opt,name=EndDay" json:"EndDay,omitempty"`
	ConfigId         *int32                 `protobuf:"varint,5,req,name=ConfigId" json:"ConfigId,omitempty"`
	ExcludeGameIds   []int32                `protobuf:"varint,6,rep,name=ExcludeGameIds" json:"ExcludeGameIds,omitempty"`
	Recharges        []*WeekendRechargeItme `protobuf:"bytes,7,rep,name=Recharges" json:"Recharges,omitempty"`
	Status           *CommonStatus          `protobuf:"varint,8,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *WeekendRechargeInfo) Reset()                    { *m = WeekendRechargeInfo{} }
func (m *WeekendRechargeInfo) String() string            { return proto.CompactTextString(m) }
func (*WeekendRechargeInfo) ProtoMessage()               {}
func (*WeekendRechargeInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{9} }

func (m *WeekendRechargeInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *WeekendRechargeInfo) GetLocker() int32 {
	if m != nil && m.Locker != nil {
		return *m.Locker
	}
	return 0
}

func (m *WeekendRechargeInfo) GetStartDay() int32 {
	if m != nil && m.StartDay != nil {
		return *m.StartDay
	}
	return 0
}

func (m *WeekendRechargeInfo) GetEndDay() int32 {
	if m != nil && m.EndDay != nil {
		return *m.EndDay
	}
	return 0
}

func (m *WeekendRechargeInfo) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *WeekendRechargeInfo) GetExcludeGameIds() []int32 {
	if m != nil {
		return m.ExcludeGameIds
	}
	return nil
}

func (m *WeekendRechargeInfo) GetRecharges() []*WeekendRechargeItme {
	if m != nil {
		return m.Recharges
	}
	return nil
}

func (m *WeekendRechargeInfo) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

type ManyRechargeItme struct {
	Id               *int32        `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Recharge         *int32        `protobuf:"varint,2,req,name=Recharge" json:"Recharge,omitempty"`
	Extra            *int32        `protobuf:"varint,3,req,name=Extra" json:"Extra,omitempty"`
	Status           *CommonStatus `protobuf:"varint,4,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	WareId           *string       `protobuf:"bytes,5,req,name=WareId" json:"WareId,omitempty"`
	Locker           *int32        `protobuf:"varint,6,req,name=Locker" json:"Locker,omitempty"`
	NeedCount        *int32        `protobuf:"varint,7,req,name=NeedCount" json:"NeedCount,omitempty"`
	RechargeCount    *int32        `protobuf:"varint,8,req,name=RechargeCount" json:"RechargeCount,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ManyRechargeItme) Reset()                    { *m = ManyRechargeItme{} }
func (m *ManyRechargeItme) String() string            { return proto.CompactTextString(m) }
func (*ManyRechargeItme) ProtoMessage()               {}
func (*ManyRechargeItme) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{10} }

func (m *ManyRechargeItme) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ManyRechargeItme) GetRecharge() int32 {
	if m != nil && m.Recharge != nil {
		return *m.Recharge
	}
	return 0
}

func (m *ManyRechargeItme) GetExtra() int32 {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return 0
}

func (m *ManyRechargeItme) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *ManyRechargeItme) GetWareId() string {
	if m != nil && m.WareId != nil {
		return *m.WareId
	}
	return ""
}

func (m *ManyRechargeItme) GetLocker() int32 {
	if m != nil && m.Locker != nil {
		return *m.Locker
	}
	return 0
}

func (m *ManyRechargeItme) GetNeedCount() int32 {
	if m != nil && m.NeedCount != nil {
		return *m.NeedCount
	}
	return 0
}

func (m *ManyRechargeItme) GetRechargeCount() int32 {
	if m != nil && m.RechargeCount != nil {
		return *m.RechargeCount
	}
	return 0
}

type ManyRechargeInfo struct {
	IsOpen           *bool               `protobuf:"varint,1,req,name=IsOpen" json:"IsOpen,omitempty"`
	StartDay         *int32              `protobuf:"varint,2,req,name=StartDay" json:"StartDay,omitempty"`
	EndDay           *int32              `protobuf:"varint,3,opt,name=EndDay" json:"EndDay,omitempty"`
	ConfigId         *int32              `protobuf:"varint,4,req,name=ConfigId" json:"ConfigId,omitempty"`
	Recharges        []*ManyRechargeItme `protobuf:"bytes,5,rep,name=Recharges" json:"Recharges,omitempty"`
	Status           *CommonStatus       `protobuf:"varint,6,req,name=Status,enum=VK.Proto.CommonStatus" json:"Status,omitempty"`
	ExcludeGameIds   []int32             `protobuf:"varint,7,rep,name=ExcludeGameIds" json:"ExcludeGameIds,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ManyRechargeInfo) Reset()                    { *m = ManyRechargeInfo{} }
func (m *ManyRechargeInfo) String() string            { return proto.CompactTextString(m) }
func (*ManyRechargeInfo) ProtoMessage()               {}
func (*ManyRechargeInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{11} }

func (m *ManyRechargeInfo) GetIsOpen() bool {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return false
}

func (m *ManyRechargeInfo) GetStartDay() int32 {
	if m != nil && m.StartDay != nil {
		return *m.StartDay
	}
	return 0
}

func (m *ManyRechargeInfo) GetEndDay() int32 {
	if m != nil && m.EndDay != nil {
		return *m.EndDay
	}
	return 0
}

func (m *ManyRechargeInfo) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *ManyRechargeInfo) GetRecharges() []*ManyRechargeItme {
	if m != nil {
		return m.Recharges
	}
	return nil
}

func (m *ManyRechargeInfo) GetStatus() CommonStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CommonStatus_CS_Invalid
}

func (m *ManyRechargeInfo) GetExcludeGameIds() []int32 {
	if m != nil {
		return m.ExcludeGameIds
	}
	return nil
}

func init() {
	proto.RegisterType((*WeekRechargeTask)(nil), "VK.Proto.WeekRechargeTask")
	proto.RegisterType((*WeekRechargeInfo)(nil), "VK.Proto.WeekRechargeInfo")
	proto.RegisterType((*WeekRechargeTaskReq)(nil), "VK.Proto.WeekRechargeTaskReq")
	proto.RegisterType((*WeekRechargeTaskResp)(nil), "VK.Proto.WeekRechargeTaskResp")
	proto.RegisterType((*RechargeExtraInfo)(nil), "VK.Proto.RechargeExtraInfo")
	proto.RegisterType((*LoadRechargeExtraReq)(nil), "VK.Proto.LoadRechargeExtraReq")
	proto.RegisterType((*MidMonthRechargeItme)(nil), "VK.Proto.MidMonthRechargeItme")
	proto.RegisterType((*MidMonthRechargeInfo)(nil), "VK.Proto.MidMonthRechargeInfo")
	proto.RegisterType((*WeekendRechargeItme)(nil), "VK.Proto.WeekendRechargeItme")
	proto.RegisterType((*WeekendRechargeInfo)(nil), "VK.Proto.WeekendRechargeInfo")
	proto.RegisterType((*ManyRechargeItme)(nil), "VK.Proto.ManyRechargeItme")
	proto.RegisterType((*ManyRechargeInfo)(nil), "VK.Proto.ManyRechargeInfo")
}

func init() { proto.RegisterFile("client_rechargeactivity.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x5f, 0x6f, 0xd2, 0x50,
	0x1c, 0x4d, 0x0b, 0x2d, 0xf0, 0x9b, 0x12, 0xbc, 0x23, 0xa4, 0x41, 0xb7, 0x34, 0x8d, 0x31, 0xc4,
	0x44, 0x5c, 0x78, 0x32, 0xd1, 0xa7, 0x01, 0x99, 0x8d, 0x63, 0x9a, 0xbb, 0xc5, 0x3d, 0x2e, 0x57,
	0x7a, 0x37, 0xc8, 0xc6, 0x2d, 0xb6, 0x45, 0xc1, 0xcf, 0xe0, 0x77, 0x70, 0xcf, 0x7e, 0x06, 0x3f,
	0xd8, 0x1e, 0x7c, 0x30, 0xf7, 0x4f, 0xa1, 0x2d, 0x30, 0x99, 0x4f, 0xf3, 0x65, 0xe3, 0xfc, 0xee,
	0xe9, 0xbd, 0xa7, 0xe7, 0x9c, 0xb6, 0xb0, 0xd3, 0xbf, 0x1a, 0x52, 0x16, 0x9d, 0x05, 0xb4, 0x3f,
	0x20, 0xc1, 0x05, 0x25, 0xfd, 0x68, 0xf8, 0x65, 0x18, 0xcd, 0x9a, 0xe3, 0xc0, 0x8f, 0x7c, 0x54,
	0xfc, 0xf8, 0xae, 0xf9, 0x81, 0xff, 0xaa, 0x6f, 0x87, 0x03, 0x12, 0x50, 0xef, 0xac, 0xef, 0x8f,
	0x46, 0x3e, 0x93, 0xcb, 0x75, 0xa4, 0x86, 0x94, 0x4d, 0x46, 0xa1, 0x9c, 0x39, 0xd7, 0x1a, 0x54,
	0x4e, 0x29, 0xbd, 0xc4, 0x6a, 0xc7, 0x13, 0x12, 0x5e, 0xa2, 0x1a, 0x98, 0xfc, 0xbf, 0xdb, 0xb1,
	0x34, 0x5b, 0x6f, 0x18, 0x58, 0x21, 0xd4, 0x02, 0x13, 0xd3, 0xaf, 0x24, 0xf0, 0x2c, 0xdd, 0xce,
	0x35, 0xb6, 0x5a, 0xf5, 0x66, 0x7c, 0x20, 0xff, 0x3b, 0xee, 0x4e, 0xfb, 0x03, 0xc2, 0x2e, 0x68,
	0x87, 0x44, 0x04, 0x2b, 0x26, 0x6a, 0x82, 0x79, 0x1c, 0x91, 0x68, 0x12, 0x5a, 0x39, 0x5b, 0x6f,
	0x94, 0x5b, 0xb5, 0xc5, 0x35, 0x6d, 0x21, 0x4e, 0xae, 0x62, 0xc5, 0x42, 0x15, 0xc8, 0x75, 0x68,
	0x68, 0xe5, 0x6d, 0xad, 0x51, 0xc2, 0xfc, 0xa7, 0x73, 0xa3, 0xa7, 0x25, 0xba, 0xec, 0xdc, 0xe7,
	0x12, 0xdd, 0xf0, 0xfd, 0x98, 0x32, 0x21, 0xb1, 0x88, 0x15, 0x42, 0xbb, 0x00, 0x6e, 0xd8, 0x26,
	0x0c, 0xd3, 0x90, 0x46, 0x96, 0x2e, 0xd6, 0x12, 0x93, 0x3b, 0xcb, 0xa9, 0x81, 0x79, 0x34, 0x19,
	0x7d, 0xa2, 0x81, 0x50, 0x64, 0x60, 0x85, 0x90, 0x05, 0x85, 0xfd, 0xc9, 0xac, 0x43, 0x22, 0x6a,
	0x19, 0x42, 0x6a, 0x0c, 0xd1, 0x1e, 0x18, 0xdc, 0xae, 0xd0, 0x32, 0xb3, 0x1e, 0x65, 0x7d, 0xc6,
	0x92, 0x88, 0xf6, 0xa0, 0x20, 0x4f, 0x6b, 0x59, 0x85, 0x5b, 0x45, 0xc5, 0x34, 0x79, 0xf7, 0x1d,
	0x9f, 0x51, 0xab, 0x18, 0xdf, 0x3d, 0x47, 0xc8, 0x81, 0x07, 0x6d, 0xc2, 0xf6, 0x27, 0xb3, 0x53,
	0x12, 0x50, 0xd7, 0xb3, 0x4a, 0xb6, 0xde, 0x28, 0xe1, 0xd4, 0x0c, 0x3d, 0x87, 0x8a, 0xc4, 0x6f,
	0xc9, 0xd5, 0xb9, 0xe2, 0x81, 0xe0, 0x2d, 0xcd, 0x9d, 0x17, 0xb0, 0xbd, 0x24, 0x9a, 0x7e, 0x5e,
	0xd7, 0x0f, 0xe7, 0x1b, 0x54, 0x97, 0xe9, 0xe1, 0x38, 0xd1, 0x1b, 0xed, 0x0e, 0xbd, 0xc9, 0xf3,
	0xa0, 0x45, 0x84, 0x6b, 0x5d, 0xe4, 0x0c, 0x2c, 0x78, 0xce, 0x2f, 0x1d, 0x1e, 0xc5, 0xe3, 0xee,
	0x34, 0x0a, 0xc8, 0xad, 0x35, 0xa9, 0x81, 0x79, 0xe8, 0xf7, 0x2f, 0x69, 0x20, 0xf6, 0x37, 0xb0,
	0x42, 0xc8, 0x86, 0xad, 0xde, 0x90, 0xc5, 0xfb, 0x88, 0x8e, 0x18, 0x38, 0x39, 0x42, 0x75, 0x28,
	0xf6, 0xc8, 0x54, 0x9c, 0xa0, 0x2a, 0x31, 0xc7, 0xa8, 0x0a, 0x86, 0x5c, 0xe0, 0x95, 0xd0, 0xb0,
	0x04, 0xfc, 0x8a, 0xb6, 0xcf, 0xce, 0x87, 0x17, 0xae, 0x67, 0x99, 0x62, 0xc3, 0x39, 0x46, 0xcf,
	0xa0, 0xdc, 0x9d, 0xf6, 0xaf, 0x26, 0x1e, 0x3d, 0x20, 0x23, 0xea, 0x7a, 0xa1, 0x55, 0xb0, 0x73,
	0x0d, 0x03, 0x67, 0xa6, 0x89, 0xda, 0x16, 0x37, 0xaa, 0xed, 0x4b, 0xc8, 0x9f, 0xcc, 0xc6, 0xd4,
	0x2a, 0xd9, 0x5a, 0xa3, 0xdc, 0x7a, 0xbc, 0x60, 0xa7, 0x2c, 0xe2, 0x14, 0x2c, 0x88, 0xce, 0x01,
	0x54, 0x0f, 0x7d, 0xe2, 0xa5, 0x96, 0x79, 0xd4, 0xf1, 0x46, 0x9a, 0x38, 0x76, 0x83, 0x8d, 0xae,
	0x35, 0xa8, 0xf6, 0x86, 0x5e, 0xcf, 0x67, 0xd1, 0x60, 0x1e, 0x53, 0x34, 0xa2, 0xa8, 0x0c, 0xba,
	0xeb, 0xa9, 0xc2, 0xe8, 0xae, 0xc7, 0x6d, 0x99, 0xfb, 0x2c, 0x43, 0x98, 0xe3, 0x85, 0x91, 0x32,
	0x00, 0x65, 0xe4, 0xc2, 0x84, 0xfc, 0xa6, 0xcf, 0xae, 0xea, 0xb7, 0x21, 0xfa, 0xad, 0x90, 0xf3,
	0x7b, 0x95, 0xc4, 0x7f, 0x69, 0x4b, 0x1d, 0x8a, 0xc7, 0x11, 0x09, 0xa2, 0x0e, 0x99, 0x29, 0xa5,
	0x73, 0xcc, 0xaf, 0xe9, 0x32, 0x8f, 0xaf, 0xa8, 0x17, 0x87, 0x44, 0xa9, 0x36, 0x18, 0x7f, 0x6d,
	0x83, 0xb9, 0xb2, 0x0d, 0x6f, 0xa0, 0x14, 0xeb, 0x96, 0x85, 0xd9, 0x6a, 0xed, 0x2e, 0xbc, 0x58,
	0xe5, 0x3e, 0x5e, 0x5c, 0xe0, 0xfc, 0xd0, 0xe4, 0x53, 0x4d, 0x99, 0x77, 0x4f, 0x03, 0xfa, 0xa9,
	0x2f, 0x2b, 0xfc, 0x9f, 0xf2, 0x79, 0xbd, 0x9c, 0xcf, 0x4e, 0xfa, 0x05, 0x96, 0xf1, 0x3e, 0x11,
	0xcf, 0x5d, 0x1f, 0x75, 0xe7, 0x46, 0x83, 0x4a, 0x8f, 0xb0, 0xd9, 0xfd, 0xcc, 0x32, 0x91, 0x8d,
	0x99, 0xca, 0xe6, 0x09, 0x94, 0x8e, 0x28, 0xf5, 0xda, 0xfe, 0x84, 0x45, 0xe2, 0xb3, 0x67, 0xe0,
	0xc5, 0x00, 0x3d, 0x85, 0x87, 0xb1, 0x3e, 0xc9, 0x28, 0x0a, 0x46, 0x7a, 0xe8, 0x7c, 0xd7, 0x33,
	0xb7, 0x7e, 0x5b, 0x49, 0x92, 0x65, 0xd0, 0xd7, 0x96, 0x21, 0xb7, 0xb6, 0x0c, 0xf9, 0x4c, 0x19,
	0x5e, 0x25, 0x43, 0x36, 0xb2, 0xdf, 0xb5, 0x6c, 0x22, 0xab, 0x13, 0x36, 0x37, 0xb2, 0x76, 0xc3,
	0x8f, 0xc4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x3f, 0xa8, 0x24, 0x1e, 0x0a, 0x00, 0x00,
}
