// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_payment.proto

package VK_Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 订单状态
type PayStateType int32

const (
	// 0作为保留类型
	// 等待支付
	PayStateType_PayStateInit PayStateType = 1
	// 支付超时
	PayStateType_PayStateTimeOut PayStateType = 2
	// 支付完成 等待发货
	PayStateType_PayStateWait PayStateType = 3
	// 已发货
	PayStateType_PayStateCompleted PayStateType = 4
)

var PayStateType_name = map[int32]string{
	1: "PayStateInit",
	2: "PayStateTimeOut",
	3: "PayStateWait",
	4: "PayStateCompleted",
}
var PayStateType_value = map[string]int32{
	"PayStateInit":      1,
	"PayStateTimeOut":   2,
	"PayStateWait":      3,
	"PayStateCompleted": 4,
}

func (x PayStateType) Enum() *PayStateType {
	p := new(PayStateType)
	*p = x
	return p
}
func (x PayStateType) String() string {
	return proto.EnumName(PayStateType_name, int32(x))
}
func (x *PayStateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PayStateType_value, data, "PayStateType")
	if err != nil {
		return err
	}
	*x = PayStateType(value)
	return nil
}
func (PayStateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

// 订单
type VNOrder struct {
	// 订单唯一ID，由服务器生成UUID
	ID *string `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	// 订单创建时间，由服务器填充
	CreateTime *uint64 `protobuf:"varint,2,req,name=CreateTime" json:"CreateTime,omitempty"`
	// 货品ID
	GoodsID *string `protobuf:"bytes,3,req,name=GoodsID" json:"GoodsID,omitempty"`
	// 购买的货品数量
	GoodsCount *uint32 `protobuf:"varint,4,req,name=GoodsCount" json:"GoodsCount,omitempty"`
	// 货品单价
	GoodsPrice *float64 `protobuf:"fixed64,5,req,name=GoodsPrice" json:"GoodsPrice,omitempty"`
	// 货品总价
	TotalPrice *float64 `protobuf:"fixed64,6,req,name=TotalPrice" json:"TotalPrice,omitempty"`
	// 第三方支付URL
	PayThirdPartyURL *string `protobuf:"bytes,7,req,name=PayThirdPartyURL" json:"PayThirdPartyURL,omitempty"`
	// 支付渠道 (详见配置)
	PayChannel *uint32 `protobuf:"varint,8,req,name=PayChannel" json:"PayChannel,omitempty"`
	// 第三方支付URL
	ThirdPartyOrderNo *string `protobuf:"bytes,9,req,name=ThirdPartyOrderNo" json:"ThirdPartyOrderNo,omitempty"`
	// 支付状态，当前订单的支付状态 (详见PayStateType)
	PayState *uint32 `protobuf:"varint,10,req,name=PayState" json:"PayState,omitempty"`
	// 订单支付状态变更时间，由服务器填充
	PayStateTime *uint64 `protobuf:"varint,11,req,name=PayStateTime" json:"PayStateTime,omitempty"`
	// 订单的发货状态
	ShippingState *uint32 `protobuf:"varint,12,opt,name=ShippingState" json:"ShippingState,omitempty"`
	// 发货时间，服务器发货完成后，填充当前时间
	ShippingTime     *uint64 `protobuf:"varint,13,opt,name=ShippingTime" json:"ShippingTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VNOrder) Reset()                    { *m = VNOrder{} }
func (m *VNOrder) String() string            { return proto.CompactTextString(m) }
func (*VNOrder) ProtoMessage()               {}
func (*VNOrder) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *VNOrder) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *VNOrder) GetCreateTime() uint64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *VNOrder) GetGoodsID() string {
	if m != nil && m.GoodsID != nil {
		return *m.GoodsID
	}
	return ""
}

func (m *VNOrder) GetGoodsCount() uint32 {
	if m != nil && m.GoodsCount != nil {
		return *m.GoodsCount
	}
	return 0
}

func (m *VNOrder) GetGoodsPrice() float64 {
	if m != nil && m.GoodsPrice != nil {
		return *m.GoodsPrice
	}
	return 0
}

func (m *VNOrder) GetTotalPrice() float64 {
	if m != nil && m.TotalPrice != nil {
		return *m.TotalPrice
	}
	return 0
}

func (m *VNOrder) GetPayThirdPartyURL() string {
	if m != nil && m.PayThirdPartyURL != nil {
		return *m.PayThirdPartyURL
	}
	return ""
}

func (m *VNOrder) GetPayChannel() uint32 {
	if m != nil && m.PayChannel != nil {
		return *m.PayChannel
	}
	return 0
}

func (m *VNOrder) GetThirdPartyOrderNo() string {
	if m != nil && m.ThirdPartyOrderNo != nil {
		return *m.ThirdPartyOrderNo
	}
	return ""
}

func (m *VNOrder) GetPayState() uint32 {
	if m != nil && m.PayState != nil {
		return *m.PayState
	}
	return 0
}

func (m *VNOrder) GetPayStateTime() uint64 {
	if m != nil && m.PayStateTime != nil {
		return *m.PayStateTime
	}
	return 0
}

func (m *VNOrder) GetShippingState() uint32 {
	if m != nil && m.ShippingState != nil {
		return *m.ShippingState
	}
	return 0
}

func (m *VNOrder) GetShippingTime() uint64 {
	if m != nil && m.ShippingTime != nil {
		return *m.ShippingTime
	}
	return 0
}

func init() {
	proto.RegisterType((*VNOrder)(nil), "VK.Proto.VNOrder")
	proto.RegisterEnum("VK.Proto.PayStateType", PayStateType_name, PayStateType_value)
}

func init() { proto.RegisterFile("client_payment.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xd1, 0x6a, 0xf2, 0x30,
	0x14, 0xc7, 0x69, 0xf4, 0xfb, 0xd4, 0x33, 0xbb, 0xd5, 0x6c, 0x83, 0xb0, 0x8b, 0x51, 0x64, 0x17,
	0x45, 0x86, 0x2f, 0x51, 0x61, 0x94, 0x0d, 0x2d, 0xd5, 0xb9, 0xbb, 0x8d, 0x60, 0xc3, 0x0c, 0xd4,
	0xa4, 0x64, 0xc7, 0x8b, 0x3e, 0xd9, 0x5e, 0x6f, 0x34, 0xa5, 0x36, 0xe2, 0xdd, 0x39, 0xbf, 0x7f,
	0xce, 0x2f, 0x87, 0x03, 0x77, 0xbb, 0x42, 0x0a, 0x85, 0x5f, 0x25, 0xaf, 0x0e, 0x42, 0xe1, 0xbc,
	0x34, 0x1a, 0x35, 0x1d, 0x6e, 0x5f, 0xe7, 0x69, 0x5d, 0x4d, 0x7f, 0x7b, 0x30, 0xd8, 0x2e, 0x57,
	0x26, 0x17, 0x86, 0x5e, 0x03, 0x49, 0x16, 0xcc, 0x0b, 0x49, 0x34, 0xca, 0x48, 0xb2, 0xa0, 0x8f,
	0x00, 0xb1, 0x11, 0x1c, 0xc5, 0x46, 0x1e, 0x04, 0x23, 0x21, 0x89, 0xfa, 0x99, 0x43, 0x28, 0x83,
	0xc1, 0x8b, 0xd6, 0xf9, 0x4f, 0xb2, 0x60, 0x3d, 0x3b, 0xd4, 0xb6, 0xf5, 0xa4, 0x2d, 0x63, 0x7d,
	0x54, 0xc8, 0xfa, 0x21, 0x89, 0xfc, 0xcc, 0x21, 0xa7, 0x3c, 0x35, 0x72, 0x27, 0xd8, 0xbf, 0x90,
	0x44, 0x5e, 0xe6, 0x90, 0x3a, 0xdf, 0x68, 0xe4, 0x45, 0x93, 0xff, 0x6f, 0xf2, 0x8e, 0xd0, 0x19,
	0x04, 0x29, 0xaf, 0x36, 0x7b, 0x69, 0xf2, 0x94, 0x1b, 0xac, 0xde, 0xb3, 0x37, 0x36, 0xb0, 0x2b,
	0x5c, 0xf0, 0xda, 0x95, 0xf2, 0x2a, 0xde, 0x73, 0xa5, 0x44, 0xc1, 0x86, 0xcd, 0x2e, 0x1d, 0xa1,
	0xcf, 0x30, 0xe9, 0x06, 0xec, 0x21, 0x96, 0x9a, 0x8d, 0xac, 0xec, 0x32, 0xa0, 0x0f, 0x30, 0x4c,
	0x79, 0xb5, 0x46, 0x8e, 0x82, 0x81, 0x75, 0x9d, 0x7a, 0x3a, 0x85, 0x71, 0x5b, 0xdb, 0x8b, 0x5d,
	0xd9, 0x8b, 0x9d, 0x31, 0xfa, 0x04, 0xfe, 0x7a, 0x2f, 0xcb, 0x52, 0xaa, 0xef, 0x46, 0x32, 0x0e,
	0xbd, 0xc8, 0xcf, 0xce, 0x61, 0x6d, 0x6a, 0x81, 0x35, 0xf9, 0xa1, 0x57, 0x9b, 0x5c, 0x36, 0xfb,
	0x74, 0x7e, 0xab, 0x4a, 0x41, 0x83, 0xae, 0x4f, 0x94, 0xc4, 0xc0, 0xa3, 0xb7, 0x70, 0xe3, 0xfe,
	0xbd, 0x3a, 0x62, 0x40, 0xdc, 0x67, 0x1f, 0x5c, 0x62, 0xd0, 0xa3, 0xf7, 0x30, 0x69, 0x49, 0xac,
	0x0f, 0x65, 0x21, 0x50, 0xe4, 0x41, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x12, 0x5e, 0xcc, 0x61,
	0x3a, 0x02, 0x00, 0x00,
}
