// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_service.proto

package VK_Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 游戏服务请求
type ServiceOps int32

const (
	ServiceOps_GS_Req_Invalid ServiceOps = 0
	// 记录流水
	ServiceOps_GS_Req_RecordCapitalFlow ServiceOps = 1
	// 读游戏道具
	ServiceOps_GS_Req_LoadGameProps ServiceOps = 2
	// 写游戏道具
	ServiceOps_GS_Req_ModGameProps ServiceOps = 3
	// 更新jackpot
	ServiceOps_GS_Req_LoadJackpot ServiceOps = 4
	// 客户端请求分配服务器
	ServiceOps_GS_Req_AllocServer ServiceOps = 5
	// 游戏服务器注册
	ServiceOps_GS_Req_GameRegister ServiceOps = 6
	// 游戏服务器数据刷新
	ServiceOps_GS_Req_GameUpdate ServiceOps = 7
	// 游戏桌子列表数据刷新
	ServiceOps_GS_Req_GameTableUpdate ServiceOps = 8
	// 获取游戏桌子列表数据
	ServiceOps_GS_Req_GetGameTableList ServiceOps = 9
	// 更新jackpot
	ServiceOps_GS_Req_ModJackpot ServiceOps = 10
	// 更新键值对
	ServiceOps_GS_Req_UpdateKeyValues ServiceOps = 11
	// 更新键值对
	ServiceOps_GS_Req_LoadValues ServiceOps = 12
	// 客户端请求分配服务器地址
	ServiceOps_GS_Req_AllocServerAddress ServiceOps = 13
	// 根据服务器id获取地址
	ServiceOps_GS_Req_GetServerAddress ServiceOps = 14
	// 更新HSet键值对
	ServiceOps_GS_Req_HSetUpdateValues ServiceOps = 15
	// 获取HSet键值对
	ServiceOps_GS_Req_HSetLoadValues ServiceOps = 16
	// 删除HSet键值对
	ServiceOps_GS_Req_HSetDelValues ServiceOps = 17
	// 更新HSet键值
	ServiceOps_GS_Req_HSetUpdate ServiceOps = 18
	// 获取HSet键值
	ServiceOps_GS_Req_HSetLoad ServiceOps = 19
	// 删除HSet键值
	ServiceOps_GS_Req_HSetDel ServiceOps = 20
	// 增加HList项
	ServiceOps_GS_Req_HListAdd ServiceOps = 21
	// 删除HList项
	ServiceOps_GS_Req_HListDel ServiceOps = 22
	// 获取HList全部项
	ServiceOps_GS_Req_HListLoadAll ServiceOps = 23
	// 获取HList范围项
	ServiceOps_GS_Req_HListLoadRange ServiceOps = 24
	// 获取ZSet数值
	ServiceOps_GS_Req_ZSetGetScore ServiceOps = 25
	// 更新ZSet数值
	ServiceOps_GS_Req_ZSetUpdateScore ServiceOps = 26
	// 刷新ZSet排名
	ServiceOps_GS_Req_ZSetRefreshRank ServiceOps = 27
	// 获取ZSet范围项(升序)
	ServiceOps_GS_Req_ZSetLoadRange ServiceOps = 28
	// 增加Set项
	ServiceOps_GS_Req_SetAdd ServiceOps = 29
	// 删除Set项
	ServiceOps_GS_Req_SetDel ServiceOps = 30
	// 是否在Set内
	ServiceOps_GS_Req_SetIsMember ServiceOps = 31
	// 获取Set随机项
	ServiceOps_GS_Req_SetRandom ServiceOps = 32
	// 获取Set所有项
	ServiceOps_GS_Req_SetMembers ServiceOps = 33
	// 获取ZSet范围项(降序)
	ServiceOps_GS_Req_ZSetLoadRevRange ServiceOps = 34
	// 删除HList所有项
	ServiceOps_GS_Req_HListDelAll ServiceOps = 35
	// 删除ZSet所有项
	ServiceOps_GS_Req_ZSetDelAll ServiceOps = 36
	// 删除Set所有项
	ServiceOps_GS_Req_SetDelAll ServiceOps = 37
	// 删除ZSet项
	ServiceOps_GS_Req_ZSetDel ServiceOps = 38
	// 删除HSet hash项
	ServiceOps_GS_Req_HSetDelHash ServiceOps = 39
	// 获取key对应的排名(升序)
	ServiceOps_GS_Req_ZSetGetRank ServiceOps = 40
	// 获取key对应的排名(降序)
	ServiceOps_GS_Req_ZSetGetRevRank ServiceOps = 41
	// 增加HSet键值对,没有值就增加，有值就保持原值不变，不做修改
	ServiceOps_GS_Req_HSetAdd ServiceOps = 42
	// 设置key的超时时间
	ServiceOps_GS_Req_SetExpire ServiceOps = 43
	// 获取key的超时时间
	ServiceOps_GS_Req_LoadExpire ServiceOps = 44
	// 增加HList项(在尾部加)
	ServiceOps_GS_Req_HListAddLast ServiceOps = 45
	// 删除HList头部项
	ServiceOps_GS_Req_HListPopFirst ServiceOps = 46
	// 删除HList尾部项
	ServiceOps_GS_Req_HListPopLast ServiceOps = 47
	// 通知玩家进入指定游戏
	ServiceOps_GS_Req_NotifyPlayerIntoGame ServiceOps = 48
	// HIncr HSet键值对
	ServiceOps_GS_Req_HSetIncr ServiceOps = 49
	// HIncr 游戏数据(数值类)
	ServiceOps_GS_Req_GameDataIncr ServiceOps = 50
	// HIncr 游戏数据(数值类) Load
	ServiceOps_GS_Req_GameDataLoad ServiceOps = 51
	// 加载奖池
	ServiceOps_GS_Req_LoadJackpots ServiceOps = 52
	// 覆盖奖池
	ServiceOps_GS_Req_SetJackpot ServiceOps = 53
	// 更新共享游戏数据
	ServiceOps_GS_Req_UpdateShareData ServiceOps = 54
	// 拉取共享游戏数据
	ServiceOps_GS_Req_LoadShareData ServiceOps = 55
	// 游戏服务器更新在线人数
	ServiceOps_GS_Req_GameUpdateOnlineCount ServiceOps = 100
)

var ServiceOps_name = map[int32]string{
	0:   "GS_Req_Invalid",
	1:   "GS_Req_RecordCapitalFlow",
	2:   "GS_Req_LoadGameProps",
	3:   "GS_Req_ModGameProps",
	4:   "GS_Req_LoadJackpot",
	5:   "GS_Req_AllocServer",
	6:   "GS_Req_GameRegister",
	7:   "GS_Req_GameUpdate",
	8:   "GS_Req_GameTableUpdate",
	9:   "GS_Req_GetGameTableList",
	10:  "GS_Req_ModJackpot",
	11:  "GS_Req_UpdateKeyValues",
	12:  "GS_Req_LoadValues",
	13:  "GS_Req_AllocServerAddress",
	14:  "GS_Req_GetServerAddress",
	15:  "GS_Req_HSetUpdateValues",
	16:  "GS_Req_HSetLoadValues",
	17:  "GS_Req_HSetDelValues",
	18:  "GS_Req_HSetUpdate",
	19:  "GS_Req_HSetLoad",
	20:  "GS_Req_HSetDel",
	21:  "GS_Req_HListAdd",
	22:  "GS_Req_HListDel",
	23:  "GS_Req_HListLoadAll",
	24:  "GS_Req_HListLoadRange",
	25:  "GS_Req_ZSetGetScore",
	26:  "GS_Req_ZSetUpdateScore",
	27:  "GS_Req_ZSetRefreshRank",
	28:  "GS_Req_ZSetLoadRange",
	29:  "GS_Req_SetAdd",
	30:  "GS_Req_SetDel",
	31:  "GS_Req_SetIsMember",
	32:  "GS_Req_SetRandom",
	33:  "GS_Req_SetMembers",
	34:  "GS_Req_ZSetLoadRevRange",
	35:  "GS_Req_HListDelAll",
	36:  "GS_Req_ZSetDelAll",
	37:  "GS_Req_SetDelAll",
	38:  "GS_Req_ZSetDel",
	39:  "GS_Req_HSetDelHash",
	40:  "GS_Req_ZSetGetRank",
	41:  "GS_Req_ZSetGetRevRank",
	42:  "GS_Req_HSetAdd",
	43:  "GS_Req_SetExpire",
	44:  "GS_Req_LoadExpire",
	45:  "GS_Req_HListAddLast",
	46:  "GS_Req_HListPopFirst",
	47:  "GS_Req_HListPopLast",
	48:  "GS_Req_NotifyPlayerIntoGame",
	49:  "GS_Req_HSetIncr",
	50:  "GS_Req_GameDataIncr",
	51:  "GS_Req_GameDataLoad",
	52:  "GS_Req_LoadJackpots",
	53:  "GS_Req_SetJackpot",
	54:  "GS_Req_UpdateShareData",
	55:  "GS_Req_LoadShareData",
	100: "GS_Req_GameUpdateOnlineCount",
}
var ServiceOps_value = map[string]int32{
	"GS_Req_Invalid":               0,
	"GS_Req_RecordCapitalFlow":     1,
	"GS_Req_LoadGameProps":         2,
	"GS_Req_ModGameProps":          3,
	"GS_Req_LoadJackpot":           4,
	"GS_Req_AllocServer":           5,
	"GS_Req_GameRegister":          6,
	"GS_Req_GameUpdate":            7,
	"GS_Req_GameTableUpdate":       8,
	"GS_Req_GetGameTableList":      9,
	"GS_Req_ModJackpot":            10,
	"GS_Req_UpdateKeyValues":       11,
	"GS_Req_LoadValues":            12,
	"GS_Req_AllocServerAddress":    13,
	"GS_Req_GetServerAddress":      14,
	"GS_Req_HSetUpdateValues":      15,
	"GS_Req_HSetLoadValues":        16,
	"GS_Req_HSetDelValues":         17,
	"GS_Req_HSetUpdate":            18,
	"GS_Req_HSetLoad":              19,
	"GS_Req_HSetDel":               20,
	"GS_Req_HListAdd":              21,
	"GS_Req_HListDel":              22,
	"GS_Req_HListLoadAll":          23,
	"GS_Req_HListLoadRange":        24,
	"GS_Req_ZSetGetScore":          25,
	"GS_Req_ZSetUpdateScore":       26,
	"GS_Req_ZSetRefreshRank":       27,
	"GS_Req_ZSetLoadRange":         28,
	"GS_Req_SetAdd":                29,
	"GS_Req_SetDel":                30,
	"GS_Req_SetIsMember":           31,
	"GS_Req_SetRandom":             32,
	"GS_Req_SetMembers":            33,
	"GS_Req_ZSetLoadRevRange":      34,
	"GS_Req_HListDelAll":           35,
	"GS_Req_ZSetDelAll":            36,
	"GS_Req_SetDelAll":             37,
	"GS_Req_ZSetDel":               38,
	"GS_Req_HSetDelHash":           39,
	"GS_Req_ZSetGetRank":           40,
	"GS_Req_ZSetGetRevRank":        41,
	"GS_Req_HSetAdd":               42,
	"GS_Req_SetExpire":             43,
	"GS_Req_LoadExpire":            44,
	"GS_Req_HListAddLast":          45,
	"GS_Req_HListPopFirst":         46,
	"GS_Req_HListPopLast":          47,
	"GS_Req_NotifyPlayerIntoGame":  48,
	"GS_Req_HSetIncr":              49,
	"GS_Req_GameDataIncr":          50,
	"GS_Req_GameDataLoad":          51,
	"GS_Req_LoadJackpots":          52,
	"GS_Req_SetJackpot":            53,
	"GS_Req_UpdateShareData":       54,
	"GS_Req_LoadShareData":         55,
	"GS_Req_GameUpdateOnlineCount": 100,
}

func (x ServiceOps) Enum() *ServiceOps {
	p := new(ServiceOps)
	*p = x
	return p
}
func (x ServiceOps) String() string {
	return proto.EnumName(ServiceOps_name, int32(x))
}
func (x *ServiceOps) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServiceOps_value, data, "ServiceOps")
	if err != nil {
		return err
	}
	*x = ServiceOps(value)
	return nil
}
func (ServiceOps) EnumDescriptor() ([]byte, []int) { return fileDescriptor23, []int{0} }

type KeyValue struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{0} }

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type UpdateKeyValues struct {
	Items            []*KeyValue `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UpdateKeyValues) Reset()                    { *m = UpdateKeyValues{} }
func (m *UpdateKeyValues) String() string            { return proto.CompactTextString(m) }
func (*UpdateKeyValues) ProtoMessage()               {}
func (*UpdateKeyValues) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{1} }

func (m *UpdateKeyValues) GetItems() []*KeyValue {
	if m != nil {
		return m.Items
	}
	return nil
}

type LoadValues struct {
	Keys             []string `protobuf:"bytes,1,rep,name=Keys" json:"Keys,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LoadValues) Reset()                    { *m = LoadValues{} }
func (m *LoadValues) String() string            { return proto.CompactTextString(m) }
func (*LoadValues) ProtoMessage()               {}
func (*LoadValues) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{2} }

func (m *LoadValues) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type LoadValuesResp struct {
	Items            []*KeyValue `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *LoadValuesResp) Reset()                    { *m = LoadValuesResp{} }
func (m *LoadValuesResp) String() string            { return proto.CompactTextString(m) }
func (*LoadValuesResp) ProtoMessage()               {}
func (*LoadValuesResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{3} }

func (m *LoadValuesResp) GetItems() []*KeyValue {
	if m != nil {
		return m.Items
	}
	return nil
}

// 流水（自上次记录以来）
type RecordCapitalFlow struct {
	GameId           *int32  `protobuf:"varint,1,req,name=GameId" json:"GameId,omitempty"`
	GroupId          *int32  `protobuf:"varint,2,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId         *string `protobuf:"bytes,3,req,name=ServerId" json:"ServerId,omitempty"`
	Profit           *int64  `protobuf:"varint,4,req,name=Profit" json:"Profit,omitempty"`
	Loss             *int64  `protobuf:"varint,5,req,name=Loss" json:"Loss,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordCapitalFlow) Reset()                    { *m = RecordCapitalFlow{} }
func (m *RecordCapitalFlow) String() string            { return proto.CompactTextString(m) }
func (*RecordCapitalFlow) ProtoMessage()               {}
func (*RecordCapitalFlow) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{4} }

func (m *RecordCapitalFlow) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *RecordCapitalFlow) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *RecordCapitalFlow) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *RecordCapitalFlow) GetProfit() int64 {
	if m != nil && m.Profit != nil {
		return *m.Profit
	}
	return 0
}

func (m *RecordCapitalFlow) GetLoss() int64 {
	if m != nil && m.Loss != nil {
		return *m.Loss
	}
	return 0
}

type RecordCapitalFlowRsp struct {
	Tax              *int64 `protobuf:"varint,1,req,name=Tax" json:"Tax,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RecordCapitalFlowRsp) Reset()                    { *m = RecordCapitalFlowRsp{} }
func (m *RecordCapitalFlowRsp) String() string            { return proto.CompactTextString(m) }
func (*RecordCapitalFlowRsp) ProtoMessage()               {}
func (*RecordCapitalFlowRsp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{5} }

func (m *RecordCapitalFlowRsp) GetTax() int64 {
	if m != nil && m.Tax != nil {
		return *m.Tax
	}
	return 0
}

// 注册
type RegisterGame struct {
	GroupId          *int32  `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId         *string `protobuf:"bytes,2,req,name=ServerId" json:"ServerId,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=Port" json:"Port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterGame) Reset()                    { *m = RegisterGame{} }
func (m *RegisterGame) String() string            { return proto.CompactTextString(m) }
func (*RegisterGame) ProtoMessage()               {}
func (*RegisterGame) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{6} }

func (m *RegisterGame) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *RegisterGame) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *RegisterGame) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

// 游戏服务保活
type GameUpdate struct {
	GroupId      *int32           `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId     *string          `protobuf:"bytes,2,req,name=ServerId" json:"ServerId,omitempty"`
	TableId      *int32           `protobuf:"varint,3,opt,name=TableId" json:"TableId,omitempty"`
	PlayerCount  *int32           `protobuf:"varint,4,req,name=PlayerCount" json:"PlayerCount,omitempty"`
	PlayerCounts []*PlayerCounter `protobuf:"bytes,5,rep,name=PlayerCounts" json:"PlayerCounts,omitempty"`
	// 在GS重启之后，确保能够继续注册端口
	Port             *int32 `protobuf:"varint,6,req,name=Port" json:"Port,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameUpdate) Reset()                    { *m = GameUpdate{} }
func (m *GameUpdate) String() string            { return proto.CompactTextString(m) }
func (*GameUpdate) ProtoMessage()               {}
func (*GameUpdate) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{7} }

func (m *GameUpdate) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameUpdate) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *GameUpdate) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *GameUpdate) GetPlayerCount() int32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

func (m *GameUpdate) GetPlayerCounts() []*PlayerCounter {
	if m != nil {
		return m.PlayerCounts
	}
	return nil
}

func (m *GameUpdate) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

// 游戏服桌子更新
type GameTableUpdate struct {
	GroupId  *int32       `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId *string      `protobuf:"bytes,2,req,name=ServerId" json:"ServerId,omitempty"`
	TbInfo   []*TableInfo `protobuf:"bytes,3,rep,name=TbInfo" json:"TbInfo,omitempty"`
	// 在GS重启之后，确保能够继续注册端口
	Port             *int32 `protobuf:"varint,4,req,name=Port" json:"Port,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameTableUpdate) Reset()                    { *m = GameTableUpdate{} }
func (m *GameTableUpdate) String() string            { return proto.CompactTextString(m) }
func (*GameTableUpdate) ProtoMessage()               {}
func (*GameTableUpdate) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{8} }

func (m *GameTableUpdate) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameTableUpdate) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *GameTableUpdate) GetTbInfo() []*TableInfo {
	if m != nil {
		return m.TbInfo
	}
	return nil
}

func (m *GameTableUpdate) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

// 覆盖奖池
type SetJackpot struct {
	GroupId          *int32 `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	Count            *int32 `protobuf:"varint,2,req,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetJackpot) Reset()                    { *m = SetJackpot{} }
func (m *SetJackpot) String() string            { return proto.CompactTextString(m) }
func (*SetJackpot) ProtoMessage()               {}
func (*SetJackpot) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{9} }

func (m *SetJackpot) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *SetJackpot) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 修改奖池
type ModJackpot struct {
	GroupId          *int32 `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	Delta            *int32 `protobuf:"varint,2,req,name=Delta" json:"Delta,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModJackpot) Reset()                    { *m = ModJackpot{} }
func (m *ModJackpot) String() string            { return proto.CompactTextString(m) }
func (*ModJackpot) ProtoMessage()               {}
func (*ModJackpot) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{10} }

func (m *ModJackpot) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *ModJackpot) GetDelta() int32 {
	if m != nil && m.Delta != nil {
		return *m.Delta
	}
	return 0
}

// 根据id获取服务器地址
type GetServerAddress struct {
	GameId           *int32  `protobuf:"varint,1,req,name=GameId" json:"GameId,omitempty"`
	GroupId          *int32  `protobuf:"varint,2,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId         *string `protobuf:"bytes,3,req,name=ServerId" json:"ServerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetServerAddress) Reset()                    { *m = GetServerAddress{} }
func (m *GetServerAddress) String() string            { return proto.CompactTextString(m) }
func (*GetServerAddress) ProtoMessage()               {}
func (*GetServerAddress) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{11} }

func (m *GetServerAddress) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GetServerAddress) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GetServerAddress) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

type GetServerAddressResp struct {
	Address          *string       `protobuf:"bytes,1,req,name=Address" json:"Address,omitempty"`
	Servers          []*ServerAddr `protobuf:"bytes,2,rep,name=Servers" json:"Servers,omitempty"`
	IntoServer       *bool         `protobuf:"varint,3,opt,name=IntoServer" json:"IntoServer,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetServerAddressResp) Reset()                    { *m = GetServerAddressResp{} }
func (m *GetServerAddressResp) String() string            { return proto.CompactTextString(m) }
func (*GetServerAddressResp) ProtoMessage()               {}
func (*GetServerAddressResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{12} }

func (m *GetServerAddressResp) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *GetServerAddressResp) GetServers() []*ServerAddr {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *GetServerAddressResp) GetIntoServer() bool {
	if m != nil && m.IntoServer != nil {
		return *m.IntoServer
	}
	return false
}

// HSet更新Values
type HSetUpdateValues struct {
	Items            []*KeyValue `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	HashName         *string     `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HSetUpdateValues) Reset()                    { *m = HSetUpdateValues{} }
func (m *HSetUpdateValues) String() string            { return proto.CompactTextString(m) }
func (*HSetUpdateValues) ProtoMessage()               {}
func (*HSetUpdateValues) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{13} }

func (m *HSetUpdateValues) GetItems() []*KeyValue {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *HSetUpdateValues) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// HSet获取Values
type HSetLoadValues struct {
	Keys             []string `protobuf:"bytes,1,rep,name=Keys" json:"Keys,omitempty"`
	HashName         *string  `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HSetLoadValues) Reset()                    { *m = HSetLoadValues{} }
func (m *HSetLoadValues) String() string            { return proto.CompactTextString(m) }
func (*HSetLoadValues) ProtoMessage()               {}
func (*HSetLoadValues) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{14} }

func (m *HSetLoadValues) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *HSetLoadValues) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// HSet获取Values返回
type HSetLoadValuesResp struct {
	Items            []*KeyValue `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HSetLoadValuesResp) Reset()                    { *m = HSetLoadValuesResp{} }
func (m *HSetLoadValuesResp) String() string            { return proto.CompactTextString(m) }
func (*HSetLoadValuesResp) ProtoMessage()               {}
func (*HSetLoadValuesResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{15} }

func (m *HSetLoadValuesResp) GetItems() []*KeyValue {
	if m != nil {
		return m.Items
	}
	return nil
}

// HSet删除Values
type HSetDelValues struct {
	Keys             []string `protobuf:"bytes,1,rep,name=Keys" json:"Keys,omitempty"`
	HashName         *string  `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HSetDelValues) Reset()                    { *m = HSetDelValues{} }
func (m *HSetDelValues) String() string            { return proto.CompactTextString(m) }
func (*HSetDelValues) ProtoMessage()               {}
func (*HSetDelValues) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{16} }

func (m *HSetDelValues) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *HSetDelValues) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// HSet更新Value
type HSetUpdateValue struct {
	Item             *KeyValue `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	HashName         *string   `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *HSetUpdateValue) Reset()                    { *m = HSetUpdateValue{} }
func (m *HSetUpdateValue) String() string            { return proto.CompactTextString(m) }
func (*HSetUpdateValue) ProtoMessage()               {}
func (*HSetUpdateValue) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{17} }

func (m *HSetUpdateValue) GetItem() *KeyValue {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *HSetUpdateValue) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// HSet获取Value
type HSetLoadValue struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	HashName         *string `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HSetLoadValue) Reset()                    { *m = HSetLoadValue{} }
func (m *HSetLoadValue) String() string            { return proto.CompactTextString(m) }
func (*HSetLoadValue) ProtoMessage()               {}
func (*HSetLoadValue) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{18} }

func (m *HSetLoadValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HSetLoadValue) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// HSet获取Value返回
type HSetLoadValueResp struct {
	Item             *KeyValue `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *HSetLoadValueResp) Reset()                    { *m = HSetLoadValueResp{} }
func (m *HSetLoadValueResp) String() string            { return proto.CompactTextString(m) }
func (*HSetLoadValueResp) ProtoMessage()               {}
func (*HSetLoadValueResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{19} }

func (m *HSetLoadValueResp) GetItem() *KeyValue {
	if m != nil {
		return m.Item
	}
	return nil
}

// HSet删除Value
type HSetDelValue struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	HashName         *string `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HSetDelValue) Reset()                    { *m = HSetDelValue{} }
func (m *HSetDelValue) String() string            { return proto.CompactTextString(m) }
func (*HSetDelValue) ProtoMessage()               {}
func (*HSetDelValue) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{20} }

func (m *HSetDelValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HSetDelValue) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// 增加HList项
type HListAdd struct {
	Item             *string `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,3,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListAdd) Reset()                    { *m = HListAdd{} }
func (m *HListAdd) String() string            { return proto.CompactTextString(m) }
func (*HListAdd) ProtoMessage()               {}
func (*HListAdd) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{21} }

func (m *HListAdd) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

func (m *HListAdd) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListAdd) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// 获取HList范围项
type HListLoadRange struct {
	From             *int32  `protobuf:"varint,1,req,name=From" json:"From,omitempty"`
	To               *int32  `protobuf:"varint,2,req,name=To" json:"To,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,4,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListLoadRange) Reset()                    { *m = HListLoadRange{} }
func (m *HListLoadRange) String() string            { return proto.CompactTextString(m) }
func (*HListLoadRange) ProtoMessage()               {}
func (*HListLoadRange) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{22} }

func (m *HListLoadRange) GetFrom() int32 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *HListLoadRange) GetTo() int32 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func (m *HListLoadRange) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListLoadRange) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// 获取HList范围项返回
type HListLoadRangeResp struct {
	Items            []string `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HListLoadRangeResp) Reset()                    { *m = HListLoadRangeResp{} }
func (m *HListLoadRangeResp) String() string            { return proto.CompactTextString(m) }
func (*HListLoadRangeResp) ProtoMessage()               {}
func (*HListLoadRangeResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{23} }

func (m *HListLoadRangeResp) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

// 获取HList全部项
type HListLoadAll struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,2,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListLoadAll) Reset()                    { *m = HListLoadAll{} }
func (m *HListLoadAll) String() string            { return proto.CompactTextString(m) }
func (*HListLoadAll) ProtoMessage()               {}
func (*HListLoadAll) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{24} }

func (m *HListLoadAll) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListLoadAll) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// 获取HList全部项返回
type HListLoadAllResp struct {
	Items            []string `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HListLoadAllResp) Reset()                    { *m = HListLoadAllResp{} }
func (m *HListLoadAllResp) String() string            { return proto.CompactTextString(m) }
func (*HListLoadAllResp) ProtoMessage()               {}
func (*HListLoadAllResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{25} }

func (m *HListLoadAllResp) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

// HList删除项
type HListDel struct {
	Item             *string `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,3,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListDel) Reset()                    { *m = HListDel{} }
func (m *HListDel) String() string            { return proto.CompactTextString(m) }
func (*HListDel) ProtoMessage()               {}
func (*HListDel) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{26} }

func (m *HListDel) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

func (m *HListDel) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListDel) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// ZSet数据项
type ZSetRangeData struct {
	Key              *string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Score            *int64  `protobuf:"varint,2,opt,name=Score" json:"Score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetRangeData) Reset()                    { *m = ZSetRangeData{} }
func (m *ZSetRangeData) String() string            { return proto.CompactTextString(m) }
func (*ZSetRangeData) ProtoMessage()               {}
func (*ZSetRangeData) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{27} }

func (m *ZSetRangeData) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ZSetRangeData) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// 获取ZSet范围数据项
type ZSetGetRange struct {
	From             *int32  `protobuf:"varint,1,req,name=From" json:"From,omitempty"`
	To               *int32  `protobuf:"varint,2,req,name=To" json:"To,omitempty"`
	SetName          *string `protobuf:"bytes,3,req,name=SetName" json:"SetName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetGetRange) Reset()                    { *m = ZSetGetRange{} }
func (m *ZSetGetRange) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetRange) ProtoMessage()               {}
func (*ZSetGetRange) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{28} }

func (m *ZSetGetRange) GetFrom() int32 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *ZSetGetRange) GetTo() int32 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func (m *ZSetGetRange) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

// 获取ZSet范围数据项返回
type ZSetGetRangeResp struct {
	Rank             []*ZSetRangeData `protobuf:"bytes,1,rep,name=Rank" json:"Rank,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ZSetGetRangeResp) Reset()                    { *m = ZSetGetRangeResp{} }
func (m *ZSetGetRangeResp) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetRangeResp) ProtoMessage()               {}
func (*ZSetGetRangeResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{29} }

func (m *ZSetGetRangeResp) GetRank() []*ZSetRangeData {
	if m != nil {
		return m.Rank
	}
	return nil
}

// 刷新ZSet数据项排名
type ZSetRefreshRank struct {
	Delta            *int64  `protobuf:"varint,1,req,name=Delta" json:"Delta,omitempty"`
	SetName          *string `protobuf:"bytes,2,req,name=SetName" json:"SetName,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetRefreshRank) Reset()                    { *m = ZSetRefreshRank{} }
func (m *ZSetRefreshRank) String() string            { return proto.CompactTextString(m) }
func (*ZSetRefreshRank) ProtoMessage()               {}
func (*ZSetRefreshRank) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{30} }

func (m *ZSetRefreshRank) GetDelta() int64 {
	if m != nil && m.Delta != nil {
		return *m.Delta
	}
	return 0
}

func (m *ZSetRefreshRank) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *ZSetRefreshRank) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// 刷新ZSet数据项值
type ZSetUpdateScore struct {
	Score            *int64  `protobuf:"varint,1,req,name=Score" json:"Score,omitempty"`
	SetName          *string `protobuf:"bytes,2,req,name=SetName" json:"SetName,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetUpdateScore) Reset()                    { *m = ZSetUpdateScore{} }
func (m *ZSetUpdateScore) String() string            { return proto.CompactTextString(m) }
func (*ZSetUpdateScore) ProtoMessage()               {}
func (*ZSetUpdateScore) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{31} }

func (m *ZSetUpdateScore) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ZSetUpdateScore) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *ZSetUpdateScore) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// 获取ZSet数据项值
type ZSetGetScore struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetGetScore) Reset()                    { *m = ZSetGetScore{} }
func (m *ZSetGetScore) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetScore) ProtoMessage()               {}
func (*ZSetGetScore) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{32} }

func (m *ZSetGetScore) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *ZSetGetScore) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// 获取ZSet数据项值返回
type ZSetGetScoreResp struct {
	Score            *int64 `protobuf:"varint,1,req,name=Score" json:"Score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ZSetGetScoreResp) Reset()                    { *m = ZSetGetScoreResp{} }
func (m *ZSetGetScoreResp) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetScoreResp) ProtoMessage()               {}
func (*ZSetGetScoreResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{33} }

func (m *ZSetGetScoreResp) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// 增加Set项
type SetAdd struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Item             *string `protobuf:"bytes,2,req,name=Item" json:"Item,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAdd) Reset()                    { *m = SetAdd{} }
func (m *SetAdd) String() string            { return proto.CompactTextString(m) }
func (*SetAdd) ProtoMessage()               {}
func (*SetAdd) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{34} }

func (m *SetAdd) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *SetAdd) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

// 删除Set项
type SetDel struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Item             *string `protobuf:"bytes,2,req,name=Item" json:"Item,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetDel) Reset()                    { *m = SetDel{} }
func (m *SetDel) String() string            { return proto.CompactTextString(m) }
func (*SetDel) ProtoMessage()               {}
func (*SetDel) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{35} }

func (m *SetDel) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *SetDel) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

// 是否Set项
type SetIsMember struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Item             *string `protobuf:"bytes,2,req,name=Item" json:"Item,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetIsMember) Reset()                    { *m = SetIsMember{} }
func (m *SetIsMember) String() string            { return proto.CompactTextString(m) }
func (*SetIsMember) ProtoMessage()               {}
func (*SetIsMember) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{36} }

func (m *SetIsMember) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *SetIsMember) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

// 是否Set项
type SetIsMemberResp struct {
	IsMember         *bool  `protobuf:"varint,1,req,name=IsMember" json:"IsMember,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetIsMemberResp) Reset()                    { *m = SetIsMemberResp{} }
func (m *SetIsMemberResp) String() string            { return proto.CompactTextString(m) }
func (*SetIsMemberResp) ProtoMessage()               {}
func (*SetIsMemberResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{37} }

func (m *SetIsMemberResp) GetIsMember() bool {
	if m != nil && m.IsMember != nil {
		return *m.IsMember
	}
	return false
}

// 获取Set所有项
type SetMembers struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetMembers) Reset()                    { *m = SetMembers{} }
func (m *SetMembers) String() string            { return proto.CompactTextString(m) }
func (*SetMembers) ProtoMessage()               {}
func (*SetMembers) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{38} }

func (m *SetMembers) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

// 获取Set所有项返回
type SetMembersResp struct {
	Members          []string `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SetMembersResp) Reset()                    { *m = SetMembersResp{} }
func (m *SetMembersResp) String() string            { return proto.CompactTextString(m) }
func (*SetMembersResp) ProtoMessage()               {}
func (*SetMembersResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{39} }

func (m *SetMembersResp) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

// 获取Set随机项
type SetRandom struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Count            *int32  `protobuf:"varint,2,req,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetRandom) Reset()                    { *m = SetRandom{} }
func (m *SetRandom) String() string            { return proto.CompactTextString(m) }
func (*SetRandom) ProtoMessage()               {}
func (*SetRandom) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{40} }

func (m *SetRandom) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *SetRandom) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 获取Set随机项返回
type SetRandomResp struct {
	Members          []string `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SetRandomResp) Reset()                    { *m = SetRandomResp{} }
func (m *SetRandomResp) String() string            { return proto.CompactTextString(m) }
func (*SetRandomResp) ProtoMessage()               {}
func (*SetRandomResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{41} }

func (m *SetRandomResp) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

// HList删除所有项
type HListDelAll struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,2,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListDelAll) Reset()                    { *m = HListDelAll{} }
func (m *HListDelAll) String() string            { return proto.CompactTextString(m) }
func (*HListDelAll) ProtoMessage()               {}
func (*HListDelAll) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{42} }

func (m *HListDelAll) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListDelAll) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// ZSet删除所有项
type ZSetDelAll struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetDelAll) Reset()                    { *m = ZSetDelAll{} }
func (m *ZSetDelAll) String() string            { return proto.CompactTextString(m) }
func (*ZSetDelAll) ProtoMessage()               {}
func (*ZSetDelAll) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{43} }

func (m *ZSetDelAll) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

// Set删除所有项
type SetDelAll struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetDelAll) Reset()                    { *m = SetDelAll{} }
func (m *SetDelAll) String() string            { return proto.CompactTextString(m) }
func (*SetDelAll) ProtoMessage()               {}
func (*SetDelAll) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{44} }

func (m *SetDelAll) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

// 删除ZSet数据项
type ZSetDel struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetDel) Reset()                    { *m = ZSetDel{} }
func (m *ZSetDel) String() string            { return proto.CompactTextString(m) }
func (*ZSetDel) ProtoMessage()               {}
func (*ZSetDel) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{45} }

func (m *ZSetDel) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *ZSetDel) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// HSet删除Hsah
type HSetDelHash struct {
	HashName         *string `protobuf:"bytes,1,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HSetDelHash) Reset()                    { *m = HSetDelHash{} }
func (m *HSetDelHash) String() string            { return proto.CompactTextString(m) }
func (*HSetDelHash) ProtoMessage()               {}
func (*HSetDelHash) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{46} }

func (m *HSetDelHash) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// 获取ZSet key 排名
type ZSetGetRank struct {
	SetName          *string `protobuf:"bytes,1,req,name=SetName" json:"SetName,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetGetRank) Reset()                    { *m = ZSetGetRank{} }
func (m *ZSetGetRank) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetRank) ProtoMessage()               {}
func (*ZSetGetRank) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{47} }

func (m *ZSetGetRank) GetSetName() string {
	if m != nil && m.SetName != nil {
		return *m.SetName
	}
	return ""
}

func (m *ZSetGetRank) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// 获取ZSet key 排名返回
type ZSetGetRankResp struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Score            *int64  `protobuf:"varint,2,req,name=Score" json:"Score,omitempty"`
	Rank             *int64  `protobuf:"varint,3,req,name=Rank" json:"Rank,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ZSetGetRankResp) Reset()                    { *m = ZSetGetRankResp{} }
func (m *ZSetGetRankResp) String() string            { return proto.CompactTextString(m) }
func (*ZSetGetRankResp) ProtoMessage()               {}
func (*ZSetGetRankResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{48} }

func (m *ZSetGetRankResp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ZSetGetRankResp) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ZSetGetRankResp) GetRank() int64 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

// HSet增加Value
type HSetAddValue struct {
	Item             *KeyValue `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	HashName         *string   `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *HSetAddValue) Reset()                    { *m = HSetAddValue{} }
func (m *HSetAddValue) String() string            { return proto.CompactTextString(m) }
func (*HSetAddValue) ProtoMessage()               {}
func (*HSetAddValue) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{49} }

func (m *HSetAddValue) GetItem() *KeyValue {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *HSetAddValue) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// 设置key的超时时间
type SetExpire struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Time             *int32  `protobuf:"varint,2,req,name=Time" json:"Time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetExpire) Reset()                    { *m = SetExpire{} }
func (m *SetExpire) String() string            { return proto.CompactTextString(m) }
func (*SetExpire) ProtoMessage()               {}
func (*SetExpire) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{50} }

func (m *SetExpire) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetExpire) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 获取key的超时时间
type LoadExpire struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoadExpire) Reset()                    { *m = LoadExpire{} }
func (m *LoadExpire) String() string            { return proto.CompactTextString(m) }
func (*LoadExpire) ProtoMessage()               {}
func (*LoadExpire) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{51} }

func (m *LoadExpire) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// 获取key的超时时间返回
type LoadExpireResp struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Time             *int32  `protobuf:"varint,2,req,name=Time" json:"Time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoadExpireResp) Reset()                    { *m = LoadExpireResp{} }
func (m *LoadExpireResp) String() string            { return proto.CompactTextString(m) }
func (*LoadExpireResp) ProtoMessage()               {}
func (*LoadExpireResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{52} }

func (m *LoadExpireResp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LoadExpireResp) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 删除HList头/尾部项
type HListPop struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	ListName         *string `protobuf:"bytes,2,req,name=ListName" json:"ListName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListPop) Reset()                    { *m = HListPop{} }
func (m *HListPop) String() string            { return proto.CompactTextString(m) }
func (*HListPop) ProtoMessage()               {}
func (*HListPop) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{53} }

func (m *HListPop) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HListPop) GetListName() string {
	if m != nil && m.ListName != nil {
		return *m.ListName
	}
	return ""
}

// 删除HList头/尾部项返回
type HListPopResp struct {
	Value            *string `protobuf:"bytes,1,req,name=Value" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HListPopResp) Reset()                    { *m = HListPopResp{} }
func (m *HListPopResp) String() string            { return proto.CompactTextString(m) }
func (*HListPopResp) ProtoMessage()               {}
func (*HListPopResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{54} }

func (m *HListPopResp) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// HSet更新Value（差值更新）
type HSetIncr struct {
	Item             *KeyValue `protobuf:"bytes,1,req,name=Item" json:"Item,omitempty"`
	HashName         *string   `protobuf:"bytes,2,req,name=HashName" json:"HashName,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *HSetIncr) Reset()                    { *m = HSetIncr{} }
func (m *HSetIncr) String() string            { return proto.CompactTextString(m) }
func (*HSetIncr) ProtoMessage()               {}
func (*HSetIncr) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{55} }

func (m *HSetIncr) GetItem() *KeyValue {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *HSetIncr) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

// 游戏数据(数值类Incr)更新
type GameDataIncr struct {
	GameId           *int32  `protobuf:"varint,1,req,name=GameId" json:"GameId,omitempty"`
	GroupId          *int32  `protobuf:"varint,2,req,name=GroupId" json:"GroupId,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	Value            *int64  `protobuf:"varint,4,req,name=Value" json:"Value,omitempty"`
	HashName         *string `protobuf:"bytes,5,req,name=HashName" json:"HashName,omitempty"`
	ServerId         *string `protobuf:"bytes,6,req,name=ServerId" json:"ServerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameDataIncr) Reset()                    { *m = GameDataIncr{} }
func (m *GameDataIncr) String() string            { return proto.CompactTextString(m) }
func (*GameDataIncr) ProtoMessage()               {}
func (*GameDataIncr) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{56} }

func (m *GameDataIncr) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GameDataIncr) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameDataIncr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GameDataIncr) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *GameDataIncr) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

func (m *GameDataIncr) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

// 游戏数据(数值类Incr)拉取
type GameDataLoad struct {
	GameId           *int32  `protobuf:"varint,1,req,name=GameId" json:"GameId,omitempty"`
	GroupId          *int32  `protobuf:"varint,2,req,name=GroupId" json:"GroupId,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	HashName         *string `protobuf:"bytes,4,req,name=HashName" json:"HashName,omitempty"`
	ServerId         *string `protobuf:"bytes,5,req,name=ServerId" json:"ServerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameDataLoad) Reset()                    { *m = GameDataLoad{} }
func (m *GameDataLoad) String() string            { return proto.CompactTextString(m) }
func (*GameDataLoad) ProtoMessage()               {}
func (*GameDataLoad) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{57} }

func (m *GameDataLoad) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GameDataLoad) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameDataLoad) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GameDataLoad) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

func (m *GameDataLoad) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

// 游戏数据(数值类Incr)拉取返回
type GameDataLoadResp struct {
	GameId           *int32  `protobuf:"varint,1,req,name=GameId" json:"GameId,omitempty"`
	GroupId          *int32  `protobuf:"varint,2,req,name=GroupId" json:"GroupId,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	Value            *int64  `protobuf:"varint,4,req,name=Value" json:"Value,omitempty"`
	HashName         *string `protobuf:"bytes,5,req,name=HashName" json:"HashName,omitempty"`
	ServerId         *string `protobuf:"bytes,6,req,name=ServerId" json:"ServerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameDataLoadResp) Reset()                    { *m = GameDataLoadResp{} }
func (m *GameDataLoadResp) String() string            { return proto.CompactTextString(m) }
func (*GameDataLoadResp) ProtoMessage()               {}
func (*GameDataLoadResp) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{58} }

func (m *GameDataLoadResp) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GameDataLoadResp) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameDataLoadResp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GameDataLoadResp) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *GameDataLoadResp) GetHashName() string {
	if m != nil && m.HashName != nil {
		return *m.HashName
	}
	return ""
}

func (m *GameDataLoadResp) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

// 游戏服务器更新在线人数
type GameUpdateOnlineCount struct {
	GroupId          *int32  `protobuf:"varint,1,req,name=GroupId" json:"GroupId,omitempty"`
	ServerId         *string `protobuf:"bytes,2,req,name=ServerId" json:"ServerId,omitempty"`
	TableId          *int32  `protobuf:"varint,3,opt,name=TableId" json:"TableId,omitempty"`
	PlayerCount      *int32  `protobuf:"varint,4,req,name=PlayerCount" json:"PlayerCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameUpdateOnlineCount) Reset()                    { *m = GameUpdateOnlineCount{} }
func (m *GameUpdateOnlineCount) String() string            { return proto.CompactTextString(m) }
func (*GameUpdateOnlineCount) ProtoMessage()               {}
func (*GameUpdateOnlineCount) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{59} }

func (m *GameUpdateOnlineCount) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GameUpdateOnlineCount) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *GameUpdateOnlineCount) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *GameUpdateOnlineCount) GetPlayerCount() int32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

func init() {
	proto.RegisterType((*KeyValue)(nil), "VK.Proto.KeyValue")
	proto.RegisterType((*UpdateKeyValues)(nil), "VK.Proto.UpdateKeyValues")
	proto.RegisterType((*LoadValues)(nil), "VK.Proto.LoadValues")
	proto.RegisterType((*LoadValuesResp)(nil), "VK.Proto.LoadValuesResp")
	proto.RegisterType((*RecordCapitalFlow)(nil), "VK.Proto.RecordCapitalFlow")
	proto.RegisterType((*RecordCapitalFlowRsp)(nil), "VK.Proto.RecordCapitalFlowRsp")
	proto.RegisterType((*RegisterGame)(nil), "VK.Proto.RegisterGame")
	proto.RegisterType((*GameUpdate)(nil), "VK.Proto.GameUpdate")
	proto.RegisterType((*GameTableUpdate)(nil), "VK.Proto.GameTableUpdate")
	proto.RegisterType((*SetJackpot)(nil), "VK.Proto.SetJackpot")
	proto.RegisterType((*ModJackpot)(nil), "VK.Proto.ModJackpot")
	proto.RegisterType((*GetServerAddress)(nil), "VK.Proto.GetServerAddress")
	proto.RegisterType((*GetServerAddressResp)(nil), "VK.Proto.GetServerAddressResp")
	proto.RegisterType((*HSetUpdateValues)(nil), "VK.Proto.HSetUpdateValues")
	proto.RegisterType((*HSetLoadValues)(nil), "VK.Proto.HSetLoadValues")
	proto.RegisterType((*HSetLoadValuesResp)(nil), "VK.Proto.HSetLoadValuesResp")
	proto.RegisterType((*HSetDelValues)(nil), "VK.Proto.HSetDelValues")
	proto.RegisterType((*HSetUpdateValue)(nil), "VK.Proto.HSetUpdateValue")
	proto.RegisterType((*HSetLoadValue)(nil), "VK.Proto.HSetLoadValue")
	proto.RegisterType((*HSetLoadValueResp)(nil), "VK.Proto.HSetLoadValueResp")
	proto.RegisterType((*HSetDelValue)(nil), "VK.Proto.HSetDelValue")
	proto.RegisterType((*HListAdd)(nil), "VK.Proto.HListAdd")
	proto.RegisterType((*HListLoadRange)(nil), "VK.Proto.HListLoadRange")
	proto.RegisterType((*HListLoadRangeResp)(nil), "VK.Proto.HListLoadRangeResp")
	proto.RegisterType((*HListLoadAll)(nil), "VK.Proto.HListLoadAll")
	proto.RegisterType((*HListLoadAllResp)(nil), "VK.Proto.HListLoadAllResp")
	proto.RegisterType((*HListDel)(nil), "VK.Proto.HListDel")
	proto.RegisterType((*ZSetRangeData)(nil), "VK.Proto.ZSetRangeData")
	proto.RegisterType((*ZSetGetRange)(nil), "VK.Proto.ZSetGetRange")
	proto.RegisterType((*ZSetGetRangeResp)(nil), "VK.Proto.ZSetGetRangeResp")
	proto.RegisterType((*ZSetRefreshRank)(nil), "VK.Proto.ZSetRefreshRank")
	proto.RegisterType((*ZSetUpdateScore)(nil), "VK.Proto.ZSetUpdateScore")
	proto.RegisterType((*ZSetGetScore)(nil), "VK.Proto.ZSetGetScore")
	proto.RegisterType((*ZSetGetScoreResp)(nil), "VK.Proto.ZSetGetScoreResp")
	proto.RegisterType((*SetAdd)(nil), "VK.Proto.SetAdd")
	proto.RegisterType((*SetDel)(nil), "VK.Proto.SetDel")
	proto.RegisterType((*SetIsMember)(nil), "VK.Proto.SetIsMember")
	proto.RegisterType((*SetIsMemberResp)(nil), "VK.Proto.SetIsMemberResp")
	proto.RegisterType((*SetMembers)(nil), "VK.Proto.SetMembers")
	proto.RegisterType((*SetMembersResp)(nil), "VK.Proto.SetMembersResp")
	proto.RegisterType((*SetRandom)(nil), "VK.Proto.SetRandom")
	proto.RegisterType((*SetRandomResp)(nil), "VK.Proto.SetRandomResp")
	proto.RegisterType((*HListDelAll)(nil), "VK.Proto.HListDelAll")
	proto.RegisterType((*ZSetDelAll)(nil), "VK.Proto.ZSetDelAll")
	proto.RegisterType((*SetDelAll)(nil), "VK.Proto.SetDelAll")
	proto.RegisterType((*ZSetDel)(nil), "VK.Proto.ZSetDel")
	proto.RegisterType((*HSetDelHash)(nil), "VK.Proto.HSetDelHash")
	proto.RegisterType((*ZSetGetRank)(nil), "VK.Proto.ZSetGetRank")
	proto.RegisterType((*ZSetGetRankResp)(nil), "VK.Proto.ZSetGetRankResp")
	proto.RegisterType((*HSetAddValue)(nil), "VK.Proto.HSetAddValue")
	proto.RegisterType((*SetExpire)(nil), "VK.Proto.SetExpire")
	proto.RegisterType((*LoadExpire)(nil), "VK.Proto.LoadExpire")
	proto.RegisterType((*LoadExpireResp)(nil), "VK.Proto.LoadExpireResp")
	proto.RegisterType((*HListPop)(nil), "VK.Proto.HListPop")
	proto.RegisterType((*HListPopResp)(nil), "VK.Proto.HListPopResp")
	proto.RegisterType((*HSetIncr)(nil), "VK.Proto.HSetIncr")
	proto.RegisterType((*GameDataIncr)(nil), "VK.Proto.GameDataIncr")
	proto.RegisterType((*GameDataLoad)(nil), "VK.Proto.GameDataLoad")
	proto.RegisterType((*GameDataLoadResp)(nil), "VK.Proto.GameDataLoadResp")
	proto.RegisterType((*GameUpdateOnlineCount)(nil), "VK.Proto.GameUpdateOnlineCount")
	proto.RegisterEnum("VK.Proto.ServiceOps", ServiceOps_name, ServiceOps_value)
}

func init() { proto.RegisterFile("server_service.proto", fileDescriptor23) }

var fileDescriptor23 = []byte{
	// 1628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5b, 0x53, 0x1b, 0xc7,
	0x12, 0x3e, 0xab, 0x0b, 0x88, 0x16, 0x97, 0x61, 0x10, 0xb0, 0xc6, 0x37, 0xce, 0x1e, 0x9b, 0x23,
	0xe3, 0x98, 0xc4, 0x4e, 0x6c, 0x27, 0xc6, 0x89, 0x43, 0x99, 0x18, 0x2b, 0x80, 0xad, 0x5a, 0x61,
	0x97, 0x8b, 0x17, 0xb2, 0xb0, 0x83, 0x51, 0xb1, 0xd2, 0x28, 0xbb, 0x6b, 0x62, 0xde, 0xf2, 0x98,
	0xa4, 0x2a, 0x6f, 0xf9, 0x01, 0x79, 0xc8, 0xff, 0xc9, 0x5f, 0x4a, 0xcd, 0x4d, 0xdb, 0xbb, 0x12,
	0xb2, 0xe5, 0x50, 0xa9, 0x3c, 0x69, 0x7b, 0x7a, 0xba, 0xfb, 0xeb, 0x9e, 0x9e, 0xee, 0x1e, 0x41,
	0x25, 0x62, 0xe1, 0x09, 0x0b, 0xf7, 0xc4, 0x4f, 0xf3, 0x80, 0xad, 0x74, 0x42, 0x1e, 0x73, 0x5a,
	0x7a, 0xb9, 0xb9, 0x52, 0x17, 0x5f, 0x0b, 0x33, 0xd1, 0x91, 0x17, 0x32, 0x7f, 0xef, 0x80, 0xb7,
	0x5a, 0xbc, 0xad, 0xd8, 0xce, 0x1d, 0x28, 0x6d, 0xb2, 0xd3, 0x97, 0x5e, 0xf0, 0x86, 0x51, 0x02,
	0xf9, 0x4d, 0x76, 0x6a, 0x5b, 0x8b, 0xb9, 0xea, 0x98, 0x2b, 0x3e, 0x69, 0x05, 0x8a, 0x27, 0x82,
	0x65, 0xe7, 0xe4, 0x9a, 0x22, 0x9c, 0x55, 0x98, 0x7a, 0xd1, 0xf1, 0xbd, 0x98, 0x19, 0xc9, 0x88,
	0x56, 0xa1, 0x58, 0x8b, 0x59, 0x2b, 0xb2, 0xad, 0xc5, 0x7c, 0xb5, 0x7c, 0x87, 0xae, 0x18, 0xab,
	0x2b, 0x66, 0x8f, 0xab, 0x36, 0x38, 0x8b, 0x00, 0x5b, 0xdc, 0xf3, 0xb5, 0x1c, 0x85, 0xc2, 0x26,
	0x3b, 0x55, 0x62, 0x63, 0xae, 0xfc, 0x76, 0x1e, 0xc0, 0x64, 0xb2, 0xc3, 0x65, 0x51, 0x67, 0x08,
	0xed, 0xbf, 0x5a, 0x30, 0xed, 0xb2, 0x03, 0x1e, 0xfa, 0x8f, 0xbd, 0x4e, 0x33, 0xf6, 0x82, 0x27,
	0x01, 0xff, 0x81, 0xce, 0xc1, 0xc8, 0x86, 0xd7, 0x62, 0x35, 0x5f, 0xfa, 0x56, 0x74, 0x35, 0x45,
	0x6d, 0x18, 0xdd, 0x08, 0xf9, 0x9b, 0x4e, 0xcd, 0x97, 0x0e, 0x16, 0x5d, 0x43, 0xd2, 0x05, 0x28,
	0x35, 0x64, 0x34, 0x6b, 0xbe, 0x9d, 0x97, 0xbe, 0x77, 0x69, 0xa1, 0xad, 0x1e, 0xf2, 0xc3, 0x66,
	0x6c, 0x17, 0x16, 0x73, 0xd5, 0xbc, 0xab, 0x29, 0xe1, 0xcb, 0x16, 0x8f, 0x22, 0xbb, 0x28, 0x57,
	0xe5, 0xb7, 0x53, 0x85, 0x4a, 0x0f, 0x1c, 0x37, 0xea, 0x88, 0x50, 0xef, 0x78, 0x6f, 0x25, 0x9c,
	0xbc, 0x2b, 0x3e, 0x9d, 0x57, 0x30, 0xee, 0xb2, 0xd7, 0xcd, 0x28, 0x66, 0xa1, 0x40, 0x87, 0xb1,
	0x59, 0x67, 0x63, 0xcb, 0x65, 0xb0, 0x51, 0x28, 0xd4, 0x79, 0x18, 0x4b, 0xcc, 0x45, 0x57, 0x7e,
	0x3b, 0x7f, 0x5a, 0x00, 0x42, 0xa5, 0x3a, 0xb3, 0x0f, 0x54, 0x6c, 0xc3, 0xe8, 0x8e, 0xb7, 0x1f,
	0x30, 0x19, 0x0f, 0x4b, 0x48, 0x69, 0x92, 0x2e, 0x42, 0xb9, 0x1e, 0x78, 0xa7, 0x2c, 0x7c, 0xcc,
	0xdf, 0xb4, 0x55, 0x4c, 0x8a, 0x2e, 0x5e, 0xa2, 0xab, 0x30, 0x8e, 0x48, 0x11, 0x20, 0x71, 0x8a,
	0xf3, 0xc9, 0x29, 0x22, 0x2e, 0x0b, 0xdd, 0xd4, 0xe6, 0xae, 0x47, 0x23, 0xc8, 0xa3, 0x9f, 0x2c,
	0x98, 0x12, 0x1e, 0x49, 0x08, 0x7f, 0xcb, 0xad, 0x9b, 0x30, 0xb2, 0xb3, 0x5f, 0x6b, 0x1f, 0x72,
	0x3b, 0x2f, 0x41, 0xcd, 0x24, 0xa0, 0x94, 0x7f, 0xed, 0x43, 0xee, 0xea, 0x2d, 0x5d, 0x28, 0x05,
	0x04, 0xe5, 0x21, 0x40, 0x83, 0xc5, 0xdf, 0x7a, 0x07, 0xc7, 0x1d, 0x1e, 0x0f, 0x00, 0x51, 0x81,
	0xa2, 0x8a, 0x8f, 0x4a, 0x34, 0x45, 0x08, 0xe9, 0x6d, 0xee, 0xbf, 0x97, 0xf4, 0x3a, 0x0b, 0x62,
	0xcf, 0x48, 0x4b, 0xc2, 0xf9, 0x0e, 0xc8, 0x06, 0x8b, 0x95, 0x2f, 0x6b, 0xbe, 0x1f, 0xb2, 0x28,
	0x3a, 0xdf, 0x54, 0x77, 0x7e, 0xb4, 0xa0, 0x92, 0x35, 0x21, 0x6f, 0xa4, 0x0d, 0xa3, 0x9a, 0xd4,
	0xe5, 0xc2, 0x90, 0x74, 0x05, 0x46, 0xd5, 0xf6, 0xc8, 0xce, 0xc9, 0x90, 0x56, 0x92, 0x90, 0x26,
	0x7a, 0x5c, 0xb3, 0x89, 0x5e, 0x01, 0xa8, 0xb5, 0x63, 0xae, 0x48, 0x99, 0x5b, 0x25, 0x17, 0xad,
	0x38, 0xaf, 0x80, 0x3c, 0x6d, 0xb0, 0x58, 0x9d, 0xf2, 0xb0, 0xd5, 0x46, 0x38, 0xf7, 0xd4, 0x8b,
	0x8e, 0x9e, 0x79, 0x2d, 0x53, 0xc3, 0xba, 0xb4, 0xf3, 0x35, 0x4c, 0x0a, 0xcd, 0x83, 0xab, 0xd1,
	0x40, 0x0d, 0x5f, 0x01, 0x4d, 0x6b, 0x18, 0xb2, 0x5a, 0x3d, 0x82, 0x09, 0x21, 0xbf, 0xce, 0x82,
	0x0f, 0x04, 0xf0, 0x02, 0xa6, 0x32, 0xc1, 0xa1, 0x4b, 0x50, 0x10, 0xca, 0xe5, 0xb1, 0xf4, 0x37,
	0x2e, 0xf9, 0x03, 0xd5, 0x7e, 0xa9, 0x70, 0x75, 0xfd, 0xea, 0xd3, 0x19, 0x06, 0x89, 0xaf, 0xc2,
	0x74, 0x4a, 0x5c, 0x46, 0xe5, 0x3d, 0x71, 0x39, 0x0f, 0x61, 0x1c, 0xc7, 0x64, 0x48, 0xd3, 0x5b,
	0x50, 0x7a, 0xba, 0xd5, 0x8c, 0xe2, 0x35, 0x5f, 0xd6, 0xc2, 0xae, 0xc5, 0x31, 0xed, 0xb5, 0xd6,
	0x96, 0x4b, 0x69, 0x13, 0x02, 0x52, 0x9b, 0x4e, 0x7f, 0x43, 0x3b, 0xfb, 0x30, 0x29, 0xb5, 0x09,
	0x4f, 0x5c, 0xaf, 0xfd, 0x9a, 0x09, 0x9d, 0x4f, 0x42, 0xde, 0xd2, 0x97, 0x4b, 0x7e, 0xd3, 0x49,
	0xc8, 0xed, 0x70, 0x7d, 0xab, 0x72, 0x3b, 0xdc, 0xd8, 0xc8, 0xf7, 0xb7, 0x51, 0xc8, 0xd8, 0x58,
	0x06, 0x9a, 0xb6, 0x21, 0xa3, 0x55, 0xc1, 0x39, 0x34, 0x66, 0xf2, 0x45, 0xc4, 0xc6, 0xec, 0x5d,
	0x0b, 0x82, 0xfe, 0xb1, 0xe9, 0x5a, 0xca, 0x65, 0x2c, 0x55, 0x81, 0x60, 0xe9, 0x01, 0x76, 0x4c,
	0x14, 0xd7, 0x59, 0x70, 0x0e, 0x51, 0xbc, 0x0f, 0x13, 0xbb, 0x0d, 0x16, 0x4b, 0xe7, 0xd6, 0xbd,
	0xd8, 0x4b, 0x60, 0x5b, 0x68, 0xce, 0x68, 0x1c, 0xf0, 0x50, 0x60, 0xb6, 0xaa, 0x79, 0x57, 0x11,
	0xce, 0x16, 0x8c, 0x0b, 0xc1, 0x0d, 0x2d, 0xfb, 0x5e, 0xc1, 0xb7, 0x45, 0xf9, 0xc1, 0x38, 0x0c,
	0xe9, 0x3c, 0x02, 0x82, 0xb5, 0x49, 0xf7, 0x6f, 0x42, 0xc1, 0xf5, 0xda, 0xc7, 0xfa, 0xa6, 0xa2,
	0x8e, 0x94, 0x02, 0xec, 0xca, 0x4d, 0x4e, 0x03, 0xa6, 0xe4, 0x32, 0x3b, 0x0c, 0x59, 0x74, 0x24,
	0x96, 0x92, 0xba, 0xac, 0x1a, 0xb9, 0x22, 0x30, 0x86, 0x5c, 0x0a, 0x43, 0x6f, 0x6a, 0x18, 0xa5,
	0xea, 0x06, 0x4b, 0xb7, 0x93, 0x60, 0x68, 0xa5, 0x6a, 0x75, 0x18, 0xa5, 0x0f, 0xba, 0x81, 0xeb,
	0x91, 0xb5, 0xfa, 0xca, 0x26, 0x27, 0x29, 0xb2, 0x04, 0xcb, 0x9a, 0x2c, 0xe9, 0x45, 0xe4, 0xdc,
	0x83, 0x91, 0x06, 0x93, 0x37, 0xed, 0x6c, 0xfd, 0x26, 0x7b, 0x72, 0x49, 0xf6, 0x68, 0x39, 0x91,
	0x5b, 0xc3, 0xc9, 0xad, 0x42, 0xb9, 0xc1, 0xe2, 0x5a, 0xb4, 0xcd, 0x5a, 0xfb, 0x2c, 0x1c, 0x52,
	0xf8, 0x16, 0x4c, 0x21, 0x61, 0xe9, 0xd5, 0x02, 0x94, 0x0c, 0x2d, 0x35, 0x94, 0xdc, 0x2e, 0xed,
	0x2c, 0xc9, 0xb6, 0xae, 0x88, 0xe8, 0x6c, 0x53, 0xce, 0x32, 0x4c, 0x26, 0xfb, 0x4c, 0x67, 0xd4,
	0xa4, 0xbe, 0x53, 0x86, 0x74, 0x56, 0x61, 0x4c, 0x65, 0x95, 0xcf, 0x5b, 0x03, 0xd0, 0xf7, 0x9f,
	0x14, 0x6e, 0xc0, 0x44, 0x57, 0xf8, 0x9d, 0x76, 0xca, 0xe6, 0xf6, 0x0e, 0x5f, 0x24, 0x96, 0x00,
	0x76, 0xd5, 0xe9, 0x08, 0xd9, 0xb3, 0x1d, 0xbf, 0x2e, 0x9d, 0x79, 0xe7, 0xb6, 0xbb, 0x30, 0xba,
	0xfb, 0xce, 0xc3, 0xee, 0x4d, 0xc2, 0x1b, 0x50, 0xd6, 0x4d, 0x40, 0x54, 0xf6, 0x54, 0xc5, 0xb7,
	0x32, 0x15, 0xff, 0x0b, 0x28, 0x27, 0xd7, 0xfa, 0x78, 0x28, 0x2b, 0xdb, 0xea, 0xee, 0x69, 0x51,
	0x19, 0xd5, 0xbe, 0x4f, 0x20, 0x53, 0x9a, 0xd0, 0x6d, 0xa4, 0xba, 0x70, 0xe4, 0xd5, 0xac, 0x2f,
	0xeb, 0x83, 0xab, 0x3a, 0xd7, 0x9a, 0xef, 0x9f, 0x5f, 0x27, 0xbe, 0x2d, 0xc3, 0xfc, 0xcd, 0xdb,
	0x4e, 0x33, 0xec, 0xd7, 0x0a, 0x29, 0x14, 0x76, 0x9a, 0x5a, 0xac, 0xe8, 0xca, 0x6f, 0xe7, 0x8a,
	0x7a, 0x60, 0x9d, 0x25, 0xe3, 0xdc, 0x53, 0xcf, 0x2b, 0xc5, 0x3f, 0xc3, 0xe9, 0x7e, 0x7a, 0x3f,
	0xd7, 0x4d, 0xa1, 0xce, 0x3b, 0x43, 0xe6, 0xd4, 0x35, 0xdd, 0xb6, 0xea, 0xbc, 0x63, 0xca, 0x89,
	0xf4, 0x5f, 0xcb, 0x2b, 0xc2, 0x79, 0x06, 0x25, 0x11, 0xbe, 0x5a, 0xfb, 0x20, 0x3c, 0x97, 0xd0,
	0xfd, 0x6e, 0xc1, 0xb8, 0x18, 0x7e, 0x45, 0x05, 0x97, 0x4a, 0x87, 0x1f, 0x8d, 0x7b, 0x3b, 0x79,
	0x17, 0xba, 0x7a, 0xfa, 0x29, 0x22, 0x05, 0xa3, 0x98, 0x86, 0x91, 0x1a, 0xaf, 0x47, 0x32, 0xe3,
	0xf5, 0x2f, 0x08, 0xa2, 0x38, 0x93, 0x73, 0x81, 0x88, 0xc1, 0x14, 0x06, 0x80, 0x29, 0x66, 0xc0,
	0xfc, 0x61, 0x01, 0xc1, 0x60, 0xe4, 0x51, 0xfd, 0xfb, 0x62, 0xf6, 0xb3, 0x05, 0xb3, 0xc9, 0x6b,
	0xf6, 0x79, 0x3b, 0x68, 0xb6, 0x99, 0x7a, 0x66, 0xfe, 0xe3, 0x0f, 0xdb, 0xe5, 0xdf, 0xca, 0xa2,
	0x4d, 0xc8, 0x7f, 0x5b, 0x9e, 0x77, 0xc4, 0xf4, 0x3e, 0xb9, 0xd1, 0xd8, 0x73, 0xd9, 0xf7, 0x7b,
	0xb5, 0xf6, 0x89, 0x17, 0x34, 0x7d, 0xf2, 0x1f, 0x7a, 0x09, 0x6c, 0xbd, 0xd6, 0xf3, 0x3f, 0x00,
	0xb1, 0xa8, 0x0d, 0x15, 0xcd, 0x15, 0x11, 0x17, 0x6e, 0xd5, 0x43, 0xde, 0x89, 0x48, 0x8e, 0xce,
	0xc3, 0x8c, 0xe6, 0x6c, 0x73, 0xc4, 0xc8, 0xd3, 0x39, 0xa0, 0x48, 0x44, 0x3f, 0x1d, 0x49, 0x01,
	0xad, 0xaf, 0x05, 0x01, 0x3f, 0x50, 0xfe, 0x91, 0x22, 0x52, 0x24, 0xb4, 0x98, 0xbf, 0x18, 0xc8,
	0x08, 0x9d, 0x85, 0x69, 0xc4, 0x50, 0xe1, 0x24, 0xa3, 0x74, 0x01, 0xe6, 0xd0, 0x32, 0x7a, 0x61,
	0x93, 0x12, 0xbd, 0x08, 0xf3, 0x86, 0xc7, 0xe2, 0x2e, 0x5b, 0x5c, 0x6d, 0x32, 0x86, 0xf4, 0x25,
	0x4f, 0x5a, 0x02, 0x48, 0x5f, 0xe6, 0x3f, 0x23, 0x52, 0x46, 0x22, 0xc9, 0x13, 0x8a, 0x8c, 0xd3,
	0xcb, 0x70, 0xa1, 0xd7, 0x15, 0xfd, 0xbe, 0x24, 0x13, 0x69, 0x14, 0x69, 0xe6, 0x24, 0x62, 0x66,
	0x5f, 0x8d, 0x64, 0x8a, 0x5e, 0x80, 0x59, 0xc4, 0x44, 0x36, 0x09, 0x3a, 0x89, 0xd4, 0x8b, 0x8c,
	0x4c, 0x23, 0x90, 0x89, 0x46, 0x42, 0xe9, 0x0c, 0x4c, 0x65, 0x74, 0x91, 0x19, 0x94, 0x01, 0x5a,
	0x0b, 0xa9, 0xe0, 0x8d, 0xfa, 0x65, 0x42, 0x66, 0xb3, 0x8b, 0x62, 0xe7, 0x1c, 0x3a, 0x2a, 0x3c,
	0xa7, 0x93, 0x79, 0x8c, 0x3b, 0xf5, 0x54, 0x20, 0x36, 0x92, 0xc1, 0x53, 0x1b, 0xb9, 0x80, 0xe2,
	0x9e, 0x99, 0x2f, 0xc9, 0x42, 0x86, 0x87, 0x06, 0x5a, 0x72, 0x11, 0x05, 0x62, 0x57, 0xfb, 0xa5,
	0x4c, 0x5d, 0xa2, 0xd3, 0x30, 0xa1, 0x39, 0xaa, 0xcb, 0x91, 0xcb, 0xe9, 0x25, 0xe1, 0xc4, 0x15,
	0x94, 0x87, 0x68, 0xde, 0x22, 0x57, 0x69, 0x05, 0x48, 0xb2, 0xae, 0xe6, 0x18, 0xb2, 0x88, 0x82,
	0x9b, 0x8c, 0x51, 0xe4, 0xbf, 0xe8, 0x14, 0xbb, 0x20, 0xd8, 0x89, 0xc2, 0xe1, 0x20, 0x0b, 0x68,
	0xcc, 0x21, 0xff, 0x43, 0xba, 0x92, 0x09, 0x86, 0x5c, 0x4b, 0x1b, 0xd6, 0xab, 0xd7, 0xd1, 0x49,
	0xe9, 0xcd, 0x64, 0x09, 0x2b, 0x4e, 0x86, 0x0f, 0xf2, 0x7f, 0xb4, 0x8e, 0xc6, 0x05, 0x52, 0x45,
	0xc7, 0x62, 0xd6, 0x25, 0xc8, 0x63, 0x72, 0x23, 0x93, 0x08, 0x22, 0x58, 0xcb, 0x69, 0x20, 0xaa,
	0xfd, 0x92, 0x9b, 0x99, 0x3b, 0xa0, 0x97, 0x3f, 0xca, 0xe6, 0xc2, 0x9a, 0xef, 0x6f, 0x79, 0x51,
	0x4c, 0x6e, 0xe1, 0x44, 0xd5, 0x3d, 0xf5, 0x49, 0x33, 0x8c, 0x62, 0xb2, 0x92, 0x15, 0xa9, 0xf3,
	0x8e, 0x14, 0xf9, 0x98, 0x5e, 0x85, 0x8b, 0x9a, 0xf1, 0x8c, 0xc7, 0xcd, 0xc3, 0x53, 0x55, 0xc2,
	0x6a, 0xed, 0x98, 0x8b, 0x3b, 0x4c, 0x3e, 0xc9, 0xe4, 0xb2, 0x68, 0x96, 0xe4, 0x76, 0xa6, 0x70,
	0x98, 0x2e, 0x4a, 0xee, 0xf4, 0x61, 0xc8, 0xec, 0xff, 0x14, 0x31, 0x50, 0x69, 0x8a, 0xc8, 0x67,
	0xe9, 0x53, 0x36, 0xa5, 0xe1, 0x6e, 0x4f, 0x69, 0x68, 0x1c, 0x79, 0xa1, 0xd4, 0x47, 0xee, 0x65,
	0x2a, 0x63, 0xc2, 0xb9, 0x4f, 0x17, 0xe1, 0x52, 0x4f, 0xdd, 0x42, 0x6d, 0x80, 0xf8, 0x7f, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x3b, 0xf0, 0xea, 0x09, 0x17, 0x00, 0x00,
}
